// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Core(
  input         clock,
                reset,
                io_axi_ar_ready,
  output        io_axi_ar_valid,
  output [31:0] io_axi_ar_bits_addr,
  output        io_axi_r_ready,
  input         io_axi_r_valid,
  input  [31:0] io_axi_r_bits_data,
  input         io_axi_aw_ready,
  output        io_axi_aw_valid,
  output [31:0] io_axi_aw_bits_addr,
  input         io_axi_w_ready,
  output        io_axi_w_valid,
  output [31:0] io_axi_w_bits_data,
  output [3:0]  io_axi_w_bits_strb,
  output        io_axi_b_ready,
  input         io_axi_b_valid,
  output        io_debug_commit,
  output [31:0] io_debug_pc,
                io_debug_instr,
  output [4:0]  io_debug_rd,
  output [31:0] io_debug_wdata,
  output        io_debug_wen,
                io_halted
);

  reg  [31:0] regs_0;
  reg  [31:0] regs_1;
  reg  [31:0] regs_2;
  reg  [31:0] regs_3;
  reg  [31:0] regs_4;
  reg  [31:0] regs_5;
  reg  [31:0] regs_6;
  reg  [31:0] regs_7;
  reg  [31:0] regs_8;
  reg  [31:0] regs_9;
  reg  [31:0] regs_10;
  reg  [31:0] regs_11;
  reg  [31:0] regs_12;
  reg  [31:0] regs_13;
  reg  [31:0] regs_14;
  reg  [31:0] regs_15;
  reg  [31:0] regs_16;
  reg  [31:0] regs_17;
  reg  [31:0] regs_18;
  reg  [31:0] regs_19;
  reg  [31:0] regs_20;
  reg  [31:0] regs_21;
  reg  [31:0] regs_22;
  reg  [31:0] regs_23;
  reg  [31:0] regs_24;
  reg  [31:0] regs_25;
  reg  [31:0] regs_26;
  reg  [31:0] regs_27;
  reg  [31:0] regs_28;
  reg  [31:0] regs_29;
  reg  [31:0] regs_30;
  reg  [31:0] regs_31;
  reg  [31:0] pc;
  reg  [31:0] instr;
  reg  [31:0] memAddr;
  reg  [31:0] memWdata;
  reg  [3:0]  memStrb;
  reg  [4:0]  memRd;
  reg         memLoadSigned;
  reg  [1:0]  memLoadSize;
  reg  [31:0] nextPc;
  reg  [3:0]  state;
  reg         commitValid;
  reg  [31:0] commitPc;
  reg  [31:0] commitInstr;
  reg  [4:0]  commitRd;
  reg  [31:0] commitData;
  reg         commitWen;
  wire        _io_axi_ar_valid_T = state == 4'h0;
  wire        _io_axi_ar_bits_addr_T = state == 4'h3;
  wire        io_axi_ar_valid_0 = _io_axi_ar_valid_T | _io_axi_ar_bits_addr_T;
  wire [31:0] io_axi_aw_bits_addr_0 = memAddr & 32'hFFFFFFFC;
  wire        _io_axi_r_ready_T = state == 4'h1;
  wire        _io_axi_r_ready_T_1 = state == 4'h4;
  wire        io_axi_r_ready_0 = _io_axi_r_ready_T | _io_axi_r_ready_T_1;
  wire        io_axi_aw_valid_0 = state == 4'h5;
  wire        io_axi_w_valid_0 = state == 4'h6;
  wire        io_axi_b_ready_0 = state == 4'h7;
  always @(posedge clock) begin
    automatic logic              _r1_T;
    automatic logic [31:0][31:0] _GEN;
    automatic logic [31:0]       _GEN_0;
    automatic logic [31:0]       r1;
    automatic logic [31:0]       r2;
    automatic logic              isLoad;
    automatic logic              isStore;
    automatic logic              _GEN_1;
    automatic logic [31:0]       _fallthrough_T;
    automatic logic [31:0]       _effective_T_1;
    automatic logic              _GEN_2;
    automatic logic              _GEN_3;
    automatic logic              _GEN_4;
    _r1_T = instr[19:15] == 5'h0;
    _GEN =
      {{regs_31},
       {regs_30},
       {regs_29},
       {regs_28},
       {regs_27},
       {regs_26},
       {regs_25},
       {regs_24},
       {regs_23},
       {regs_22},
       {regs_21},
       {regs_20},
       {regs_19},
       {regs_18},
       {regs_17},
       {regs_16},
       {regs_15},
       {regs_14},
       {regs_13},
       {regs_12},
       {regs_11},
       {regs_10},
       {regs_9},
       {regs_8},
       {regs_7},
       {regs_6},
       {regs_5},
       {regs_4},
       {regs_3},
       {regs_2},
       {regs_1},
       {regs_0}};
    _GEN_0 = _GEN[instr[19:15]];
    r1 = _r1_T ? 32'h0 : _GEN_0;
    r2 = instr[24:20] == 5'h0 ? 32'h0 : _GEN[instr[24:20]];
    isLoad = instr[6:0] == 7'h3;
    isStore = instr[6:0] == 7'h23;
    _GEN_1 = state == 4'h2;
    _fallthrough_T = pc + 32'h4;
    _effective_T_1 =
      r1 + {{20{instr[31]}}, isStore ? {instr[31:25], instr[11:7]} : instr[31:20]};
    _GEN_2 = instr == 32'h100073;
    _GEN_3 = isLoad | isStore;
    _GEN_4 = _GEN_2 | isLoad;
    if (reset) begin
      regs_0 <= 32'h0;
      regs_1 <= 32'h0;
      regs_2 <= 32'h0;
      regs_3 <= 32'h0;
      regs_4 <= 32'h0;
      regs_5 <= 32'h0;
      regs_6 <= 32'h0;
      regs_7 <= 32'h0;
      regs_8 <= 32'h0;
      regs_9 <= 32'h0;
      regs_10 <= 32'h0;
      regs_11 <= 32'h0;
      regs_12 <= 32'h0;
      regs_13 <= 32'h0;
      regs_14 <= 32'h0;
      regs_15 <= 32'h0;
      regs_16 <= 32'h0;
      regs_17 <= 32'h0;
      regs_18 <= 32'h0;
      regs_19 <= 32'h0;
      regs_20 <= 32'h0;
      regs_21 <= 32'h0;
      regs_22 <= 32'h0;
      regs_23 <= 32'h0;
      regs_24 <= 32'h0;
      regs_25 <= 32'h0;
      regs_26 <= 32'h0;
      regs_27 <= 32'h0;
      regs_28 <= 32'h0;
      regs_29 <= 32'h0;
      regs_30 <= 32'h0;
      regs_31 <= 32'h0;
      pc <= 32'h80000000;
      instr <= 32'h0;
      state <= 4'h0;
      commitValid <= 1'h0;
      commitPc <= 32'h0;
      commitInstr <= 32'h0;
      commitRd <= 5'h0;
      commitData <= 32'h0;
      commitWen <= 1'h0;
    end
    else begin
      automatic logic [19:0]      _iimm_T_1;
      automatic logic [31:0]      iimm;
      automatic logic             _GEN_5;
      automatic logic             _GEN_6;
      automatic logic [31:0]      alu;
      automatic logic             _GEN_7;
      automatic logic [31:0]      _GEN_8;
      automatic logic [31:0]      _writeData_T;
      automatic logic             _GEN_9;
      automatic logic             _GEN_10;
      automatic logic [62:0]      _GEN_11;
      automatic logic             _GEN_12;
      automatic logic [31:0]      _GEN_13;
      automatic logic [62:0]      _writeData_T_10;
      automatic logic [7:0][31:0] _GEN_14;
      automatic logic [31:0]      _GEN_15;
      automatic logic             _GEN_16;
      automatic logic             _GEN_17;
      automatic logic [31:0]      _writeData_T_19;
      automatic logic [32:0]      _writeData_T_24;
      automatic logic [31:0]      _writeData_T_26;
      automatic logic [31:0]      _writeData_T_30;
      automatic logic [31:0]      _writeData_T_34;
      automatic logic [31:0]      _writeData_T_37;
      automatic logic [31:0]      _writeData_T_40;
      automatic logic [31:0]      _writeData_T_42;
      automatic logic [31:0]      _GEN_18;
      automatic logic [62:0]      _writeData_T_46;
      automatic logic [7:0][31:0] _GEN_19;
      automatic logic [31:0]      _GEN_20;
      automatic logic             _GEN_21;
      automatic logic             _GEN_22;
      automatic logic [31:0]      _GEN_23;
      automatic logic             _GEN_24;
      automatic logic             _GEN_25 = io_axi_r_ready_0 & io_axi_r_valid;
      automatic logic             _GEN_26;
      automatic logic             _GEN_27;
      automatic logic             _GEN_28;
      automatic logic             _GEN_29;
      automatic logic             _GEN_30;
      automatic logic [31:0]      raw;
      automatic logic [31:0]      narrowed;
      automatic logic             _GEN_31 = io_axi_b_ready_0 & io_axi_b_valid;
      automatic logic             _GEN_32;
      _iimm_T_1 = {20{instr[31]}};
      iimm = {_iimm_T_1, instr[31:20]};
      _GEN_5 = instr[6:0] == 7'h37;
      _GEN_6 = instr[6:0] == 7'h17;
      alu = _GEN_5 ? {instr[31:12], 12'h0} : _GEN_6 ? pc + {instr[31:12], 12'h0} : 32'h0;
      _GEN_7 = instr[6:0] == 7'h13;
      _GEN_8 = {_iimm_T_1, instr[31:20]};
      _writeData_T = r1 + _GEN_8;
      _GEN_9 = instr[14:12] == 3'h4;
      _GEN_10 = instr[14:12] == 3'h6;
      _GEN_11 = {31'h0, r1};
      _GEN_12 = instr[14:12] == 3'h5;
      _GEN_13 = {27'h0, instr[24:20]};
      _writeData_T_10 = _GEN_11 << instr[24:20];
      _GEN_14 =
        {{r1 & iimm},
         {r1 | iimm},
         {instr[30] ? $signed($signed(r1) >>> _GEN_13) : r1 >> _GEN_13},
         {r1 ^ iimm},
         {{31'h0, r1 < iimm}},
         {{31'h0, $signed(r1) < $signed(iimm)}},
         {_writeData_T_10[31:0]},
         {32'h0}};
      _GEN_15 = _GEN_14[instr[14:12]];
      _GEN_16 = instr[6:0] == 7'h33;
      _GEN_17 = instr[31:25] == 7'h1;
      _writeData_T_19 = r1 * r2;
      _writeData_T_24 = $signed({r1[31], r1}) / $signed({r2[31], r2});
      _writeData_T_26 = (|r2) ? _writeData_T_24[31:0] : 32'hFFFFFFFF;
      _writeData_T_30 = $signed(r1) % $signed(r2);
      _writeData_T_34 = r1 / r2;
      _writeData_T_37 = r1 % r2;
      _writeData_T_40 = r1 - r2;
      _writeData_T_42 = r1 + r2;
      _GEN_18 = {27'h0, r2[4:0]};
      _writeData_T_46 = _GEN_11 << r2[4:0];
      _GEN_19 =
        {{r1 & r2},
         {r1 | r2},
         {instr[30] ? $signed($signed(r1) >>> _GEN_18) : r1 >> _GEN_18},
         {r1 ^ r2},
         {{31'h0, r1 < r2}},
         {{31'h0, $signed(r1) < $signed(r2)}},
         {_writeData_T_46[31:0]},
         {32'h0}};
      _GEN_20 = _GEN_19[instr[14:12]];
      _GEN_21 = instr[6:0] == 7'h6F;
      _GEN_22 = instr[6:0] == 7'h67;
      _GEN_23 = _GEN_21 ? pc + 32'h4 : _GEN_22 ? pc + 32'h4 : 32'h0;
      _GEN_24 = _GEN_5 | _GEN_6;
      _GEN_26 = _io_axi_r_ready_T & _GEN_25;
      _GEN_27 =
        (_GEN_5 | _GEN_6 | _GEN_7 | _GEN_16 | _GEN_21 | _GEN_22) & (|(instr[11:7]));
      _GEN_28 = _GEN_2 | _GEN_3;
      _GEN_29 = ~_GEN_1 | _GEN_28;
      _GEN_30 = _io_axi_r_ready_T_1 & _GEN_25;
      raw = io_axi_r_bits_data >> {27'h0, memAddr[1:0], 3'h0};
      narrowed =
        memLoadSize == 2'h0
          ? {{24{raw[7] & memLoadSigned}}, raw[7:0]}
          : memLoadSize == 2'h1 ? {{16{raw[15] & memLoadSigned}}, raw[15:0]} : raw;
      _GEN_32 = _GEN_31 | _GEN_30;
      if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & ~(|(instr[11:7])))) begin
        if (reset)
          regs_0 <= 32'h0;
      end
      else if (_GEN_24)
        regs_0 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_0 <= _GEN_15;
        else
          regs_0 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_0 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_0 <= _writeData_T_30;
              else if (_r1_T)
                regs_0 <= 32'h0;
              else
                regs_0 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_0 <= _writeData_T_34;
              else
                regs_0 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_0 <= _writeData_T_37;
              else if (_r1_T)
                regs_0 <= 32'h0;
              else
                regs_0 <= _GEN_0;
            end
            else
              regs_0 <= 32'h0;
          end
          else
            regs_0 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_0 <= _GEN_20;
        else if (instr[30])
          regs_0 <= _writeData_T_40;
        else
          regs_0 <= _writeData_T_42;
      end
      else
        regs_0 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h1)
        regs_1 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h1)) begin
        if (reset)
          regs_1 <= 32'h0;
      end
      else if (_GEN_24)
        regs_1 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_1 <= _GEN_15;
        else
          regs_1 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_1 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_1 <= _writeData_T_30;
              else if (_r1_T)
                regs_1 <= 32'h0;
              else
                regs_1 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_1 <= _writeData_T_34;
              else
                regs_1 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_1 <= _writeData_T_37;
              else if (_r1_T)
                regs_1 <= 32'h0;
              else
                regs_1 <= _GEN_0;
            end
            else
              regs_1 <= 32'h0;
          end
          else
            regs_1 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_1 <= _GEN_20;
        else if (instr[30])
          regs_1 <= _writeData_T_40;
        else
          regs_1 <= _writeData_T_42;
      end
      else
        regs_1 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h2)
        regs_2 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h2)) begin
        if (reset)
          regs_2 <= 32'h0;
      end
      else if (_GEN_24)
        regs_2 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_2 <= _GEN_15;
        else
          regs_2 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_2 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_2 <= _writeData_T_30;
              else if (_r1_T)
                regs_2 <= 32'h0;
              else
                regs_2 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_2 <= _writeData_T_34;
              else
                regs_2 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_2 <= _writeData_T_37;
              else if (_r1_T)
                regs_2 <= 32'h0;
              else
                regs_2 <= _GEN_0;
            end
            else
              regs_2 <= 32'h0;
          end
          else
            regs_2 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_2 <= _GEN_20;
        else if (instr[30])
          regs_2 <= _writeData_T_40;
        else
          regs_2 <= _writeData_T_42;
      end
      else
        regs_2 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h3)
        regs_3 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h3)) begin
        if (reset)
          regs_3 <= 32'h0;
      end
      else if (_GEN_24)
        regs_3 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_3 <= _GEN_15;
        else
          regs_3 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_3 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_3 <= _writeData_T_30;
              else if (_r1_T)
                regs_3 <= 32'h0;
              else
                regs_3 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_3 <= _writeData_T_34;
              else
                regs_3 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_3 <= _writeData_T_37;
              else if (_r1_T)
                regs_3 <= 32'h0;
              else
                regs_3 <= _GEN_0;
            end
            else
              regs_3 <= 32'h0;
          end
          else
            regs_3 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_3 <= _GEN_20;
        else if (instr[30])
          regs_3 <= _writeData_T_40;
        else
          regs_3 <= _writeData_T_42;
      end
      else
        regs_3 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h4)
        regs_4 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h4)) begin
        if (reset)
          regs_4 <= 32'h0;
      end
      else if (_GEN_24)
        regs_4 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_4 <= _GEN_15;
        else
          regs_4 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_4 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_4 <= _writeData_T_30;
              else if (_r1_T)
                regs_4 <= 32'h0;
              else
                regs_4 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_4 <= _writeData_T_34;
              else
                regs_4 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_4 <= _writeData_T_37;
              else if (_r1_T)
                regs_4 <= 32'h0;
              else
                regs_4 <= _GEN_0;
            end
            else
              regs_4 <= 32'h0;
          end
          else
            regs_4 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_4 <= _GEN_20;
        else if (instr[30])
          regs_4 <= _writeData_T_40;
        else
          regs_4 <= _writeData_T_42;
      end
      else
        regs_4 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h5)
        regs_5 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h5)) begin
        if (reset)
          regs_5 <= 32'h0;
      end
      else if (_GEN_24)
        regs_5 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_5 <= _GEN_15;
        else
          regs_5 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_5 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_5 <= _writeData_T_30;
              else if (_r1_T)
                regs_5 <= 32'h0;
              else
                regs_5 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_5 <= _writeData_T_34;
              else
                regs_5 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_5 <= _writeData_T_37;
              else if (_r1_T)
                regs_5 <= 32'h0;
              else
                regs_5 <= _GEN_0;
            end
            else
              regs_5 <= 32'h0;
          end
          else
            regs_5 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_5 <= _GEN_20;
        else if (instr[30])
          regs_5 <= _writeData_T_40;
        else
          regs_5 <= _writeData_T_42;
      end
      else
        regs_5 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h6)
        regs_6 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h6)) begin
        if (reset)
          regs_6 <= 32'h0;
      end
      else if (_GEN_24)
        regs_6 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_6 <= _GEN_15;
        else
          regs_6 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_6 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_6 <= _writeData_T_30;
              else if (_r1_T)
                regs_6 <= 32'h0;
              else
                regs_6 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_6 <= _writeData_T_34;
              else
                regs_6 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_6 <= _writeData_T_37;
              else if (_r1_T)
                regs_6 <= 32'h0;
              else
                regs_6 <= _GEN_0;
            end
            else
              regs_6 <= 32'h0;
          end
          else
            regs_6 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_6 <= _GEN_20;
        else if (instr[30])
          regs_6 <= _writeData_T_40;
        else
          regs_6 <= _writeData_T_42;
      end
      else
        regs_6 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h7)
        regs_7 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h7)) begin
        if (reset)
          regs_7 <= 32'h0;
      end
      else if (_GEN_24)
        regs_7 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_7 <= _GEN_15;
        else
          regs_7 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_7 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_7 <= _writeData_T_30;
              else if (_r1_T)
                regs_7 <= 32'h0;
              else
                regs_7 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_7 <= _writeData_T_34;
              else
                regs_7 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_7 <= _writeData_T_37;
              else if (_r1_T)
                regs_7 <= 32'h0;
              else
                regs_7 <= _GEN_0;
            end
            else
              regs_7 <= 32'h0;
          end
          else
            regs_7 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_7 <= _GEN_20;
        else if (instr[30])
          regs_7 <= _writeData_T_40;
        else
          regs_7 <= _writeData_T_42;
      end
      else
        regs_7 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h8)
        regs_8 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h8)) begin
        if (reset)
          regs_8 <= 32'h0;
      end
      else if (_GEN_24)
        regs_8 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_8 <= _GEN_15;
        else
          regs_8 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_8 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_8 <= _writeData_T_30;
              else if (_r1_T)
                regs_8 <= 32'h0;
              else
                regs_8 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_8 <= _writeData_T_34;
              else
                regs_8 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_8 <= _writeData_T_37;
              else if (_r1_T)
                regs_8 <= 32'h0;
              else
                regs_8 <= _GEN_0;
            end
            else
              regs_8 <= 32'h0;
          end
          else
            regs_8 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_8 <= _GEN_20;
        else if (instr[30])
          regs_8 <= _writeData_T_40;
        else
          regs_8 <= _writeData_T_42;
      end
      else
        regs_8 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h9)
        regs_9 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h9)) begin
        if (reset)
          regs_9 <= 32'h0;
      end
      else if (_GEN_24)
        regs_9 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_9 <= _GEN_15;
        else
          regs_9 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_9 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_9 <= _writeData_T_30;
              else if (_r1_T)
                regs_9 <= 32'h0;
              else
                regs_9 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_9 <= _writeData_T_34;
              else
                regs_9 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_9 <= _writeData_T_37;
              else if (_r1_T)
                regs_9 <= 32'h0;
              else
                regs_9 <= _GEN_0;
            end
            else
              regs_9 <= 32'h0;
          end
          else
            regs_9 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_9 <= _GEN_20;
        else if (instr[30])
          regs_9 <= _writeData_T_40;
        else
          regs_9 <= _writeData_T_42;
      end
      else
        regs_9 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'hA)
        regs_10 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'hA)) begin
        if (reset)
          regs_10 <= 32'h0;
      end
      else if (_GEN_24)
        regs_10 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_10 <= _GEN_15;
        else
          regs_10 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_10 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_10 <= _writeData_T_30;
              else if (_r1_T)
                regs_10 <= 32'h0;
              else
                regs_10 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_10 <= _writeData_T_34;
              else
                regs_10 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_10 <= _writeData_T_37;
              else if (_r1_T)
                regs_10 <= 32'h0;
              else
                regs_10 <= _GEN_0;
            end
            else
              regs_10 <= 32'h0;
          end
          else
            regs_10 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_10 <= _GEN_20;
        else if (instr[30])
          regs_10 <= _writeData_T_40;
        else
          regs_10 <= _writeData_T_42;
      end
      else
        regs_10 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'hB)
        regs_11 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'hB)) begin
        if (reset)
          regs_11 <= 32'h0;
      end
      else if (_GEN_24)
        regs_11 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_11 <= _GEN_15;
        else
          regs_11 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_11 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_11 <= _writeData_T_30;
              else if (_r1_T)
                regs_11 <= 32'h0;
              else
                regs_11 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_11 <= _writeData_T_34;
              else
                regs_11 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_11 <= _writeData_T_37;
              else if (_r1_T)
                regs_11 <= 32'h0;
              else
                regs_11 <= _GEN_0;
            end
            else
              regs_11 <= 32'h0;
          end
          else
            regs_11 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_11 <= _GEN_20;
        else if (instr[30])
          regs_11 <= _writeData_T_40;
        else
          regs_11 <= _writeData_T_42;
      end
      else
        regs_11 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'hC)
        regs_12 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'hC)) begin
        if (reset)
          regs_12 <= 32'h0;
      end
      else if (_GEN_24)
        regs_12 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_12 <= _GEN_15;
        else
          regs_12 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_12 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_12 <= _writeData_T_30;
              else if (_r1_T)
                regs_12 <= 32'h0;
              else
                regs_12 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_12 <= _writeData_T_34;
              else
                regs_12 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_12 <= _writeData_T_37;
              else if (_r1_T)
                regs_12 <= 32'h0;
              else
                regs_12 <= _GEN_0;
            end
            else
              regs_12 <= 32'h0;
          end
          else
            regs_12 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_12 <= _GEN_20;
        else if (instr[30])
          regs_12 <= _writeData_T_40;
        else
          regs_12 <= _writeData_T_42;
      end
      else
        regs_12 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'hD)
        regs_13 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'hD)) begin
        if (reset)
          regs_13 <= 32'h0;
      end
      else if (_GEN_24)
        regs_13 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_13 <= _GEN_15;
        else
          regs_13 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_13 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_13 <= _writeData_T_30;
              else if (_r1_T)
                regs_13 <= 32'h0;
              else
                regs_13 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_13 <= _writeData_T_34;
              else
                regs_13 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_13 <= _writeData_T_37;
              else if (_r1_T)
                regs_13 <= 32'h0;
              else
                regs_13 <= _GEN_0;
            end
            else
              regs_13 <= 32'h0;
          end
          else
            regs_13 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_13 <= _GEN_20;
        else if (instr[30])
          regs_13 <= _writeData_T_40;
        else
          regs_13 <= _writeData_T_42;
      end
      else
        regs_13 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'hE)
        regs_14 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'hE)) begin
        if (reset)
          regs_14 <= 32'h0;
      end
      else if (_GEN_24)
        regs_14 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_14 <= _GEN_15;
        else
          regs_14 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_14 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_14 <= _writeData_T_30;
              else if (_r1_T)
                regs_14 <= 32'h0;
              else
                regs_14 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_14 <= _writeData_T_34;
              else
                regs_14 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_14 <= _writeData_T_37;
              else if (_r1_T)
                regs_14 <= 32'h0;
              else
                regs_14 <= _GEN_0;
            end
            else
              regs_14 <= 32'h0;
          end
          else
            regs_14 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_14 <= _GEN_20;
        else if (instr[30])
          regs_14 <= _writeData_T_40;
        else
          regs_14 <= _writeData_T_42;
      end
      else
        regs_14 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'hF)
        regs_15 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'hF)) begin
        if (reset)
          regs_15 <= 32'h0;
      end
      else if (_GEN_24)
        regs_15 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_15 <= _GEN_15;
        else
          regs_15 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_15 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_15 <= _writeData_T_30;
              else if (_r1_T)
                regs_15 <= 32'h0;
              else
                regs_15 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_15 <= _writeData_T_34;
              else
                regs_15 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_15 <= _writeData_T_37;
              else if (_r1_T)
                regs_15 <= 32'h0;
              else
                regs_15 <= _GEN_0;
            end
            else
              regs_15 <= 32'h0;
          end
          else
            regs_15 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_15 <= _GEN_20;
        else if (instr[30])
          regs_15 <= _writeData_T_40;
        else
          regs_15 <= _writeData_T_42;
      end
      else
        regs_15 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h10)
        regs_16 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h10)) begin
        if (reset)
          regs_16 <= 32'h0;
      end
      else if (_GEN_24)
        regs_16 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_16 <= _GEN_15;
        else
          regs_16 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_16 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_16 <= _writeData_T_30;
              else if (_r1_T)
                regs_16 <= 32'h0;
              else
                regs_16 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_16 <= _writeData_T_34;
              else
                regs_16 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_16 <= _writeData_T_37;
              else if (_r1_T)
                regs_16 <= 32'h0;
              else
                regs_16 <= _GEN_0;
            end
            else
              regs_16 <= 32'h0;
          end
          else
            regs_16 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_16 <= _GEN_20;
        else if (instr[30])
          regs_16 <= _writeData_T_40;
        else
          regs_16 <= _writeData_T_42;
      end
      else
        regs_16 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h11)
        regs_17 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h11)) begin
        if (reset)
          regs_17 <= 32'h0;
      end
      else if (_GEN_24)
        regs_17 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_17 <= _GEN_15;
        else
          regs_17 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_17 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_17 <= _writeData_T_30;
              else if (_r1_T)
                regs_17 <= 32'h0;
              else
                regs_17 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_17 <= _writeData_T_34;
              else
                regs_17 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_17 <= _writeData_T_37;
              else if (_r1_T)
                regs_17 <= 32'h0;
              else
                regs_17 <= _GEN_0;
            end
            else
              regs_17 <= 32'h0;
          end
          else
            regs_17 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_17 <= _GEN_20;
        else if (instr[30])
          regs_17 <= _writeData_T_40;
        else
          regs_17 <= _writeData_T_42;
      end
      else
        regs_17 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h12)
        regs_18 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h12)) begin
        if (reset)
          regs_18 <= 32'h0;
      end
      else if (_GEN_24)
        regs_18 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_18 <= _GEN_15;
        else
          regs_18 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_18 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_18 <= _writeData_T_30;
              else if (_r1_T)
                regs_18 <= 32'h0;
              else
                regs_18 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_18 <= _writeData_T_34;
              else
                regs_18 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_18 <= _writeData_T_37;
              else if (_r1_T)
                regs_18 <= 32'h0;
              else
                regs_18 <= _GEN_0;
            end
            else
              regs_18 <= 32'h0;
          end
          else
            regs_18 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_18 <= _GEN_20;
        else if (instr[30])
          regs_18 <= _writeData_T_40;
        else
          regs_18 <= _writeData_T_42;
      end
      else
        regs_18 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h13)
        regs_19 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h13)) begin
        if (reset)
          regs_19 <= 32'h0;
      end
      else if (_GEN_24)
        regs_19 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_19 <= _GEN_15;
        else
          regs_19 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_19 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_19 <= _writeData_T_30;
              else if (_r1_T)
                regs_19 <= 32'h0;
              else
                regs_19 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_19 <= _writeData_T_34;
              else
                regs_19 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_19 <= _writeData_T_37;
              else if (_r1_T)
                regs_19 <= 32'h0;
              else
                regs_19 <= _GEN_0;
            end
            else
              regs_19 <= 32'h0;
          end
          else
            regs_19 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_19 <= _GEN_20;
        else if (instr[30])
          regs_19 <= _writeData_T_40;
        else
          regs_19 <= _writeData_T_42;
      end
      else
        regs_19 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h14)
        regs_20 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h14)) begin
        if (reset)
          regs_20 <= 32'h0;
      end
      else if (_GEN_24)
        regs_20 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_20 <= _GEN_15;
        else
          regs_20 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_20 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_20 <= _writeData_T_30;
              else if (_r1_T)
                regs_20 <= 32'h0;
              else
                regs_20 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_20 <= _writeData_T_34;
              else
                regs_20 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_20 <= _writeData_T_37;
              else if (_r1_T)
                regs_20 <= 32'h0;
              else
                regs_20 <= _GEN_0;
            end
            else
              regs_20 <= 32'h0;
          end
          else
            regs_20 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_20 <= _GEN_20;
        else if (instr[30])
          regs_20 <= _writeData_T_40;
        else
          regs_20 <= _writeData_T_42;
      end
      else
        regs_20 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h15)
        regs_21 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h15)) begin
        if (reset)
          regs_21 <= 32'h0;
      end
      else if (_GEN_24)
        regs_21 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_21 <= _GEN_15;
        else
          regs_21 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_21 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_21 <= _writeData_T_30;
              else if (_r1_T)
                regs_21 <= 32'h0;
              else
                regs_21 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_21 <= _writeData_T_34;
              else
                regs_21 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_21 <= _writeData_T_37;
              else if (_r1_T)
                regs_21 <= 32'h0;
              else
                regs_21 <= _GEN_0;
            end
            else
              regs_21 <= 32'h0;
          end
          else
            regs_21 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_21 <= _GEN_20;
        else if (instr[30])
          regs_21 <= _writeData_T_40;
        else
          regs_21 <= _writeData_T_42;
      end
      else
        regs_21 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h16)
        regs_22 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h16)) begin
        if (reset)
          regs_22 <= 32'h0;
      end
      else if (_GEN_24)
        regs_22 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_22 <= _GEN_15;
        else
          regs_22 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_22 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_22 <= _writeData_T_30;
              else if (_r1_T)
                regs_22 <= 32'h0;
              else
                regs_22 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_22 <= _writeData_T_34;
              else
                regs_22 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_22 <= _writeData_T_37;
              else if (_r1_T)
                regs_22 <= 32'h0;
              else
                regs_22 <= _GEN_0;
            end
            else
              regs_22 <= 32'h0;
          end
          else
            regs_22 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_22 <= _GEN_20;
        else if (instr[30])
          regs_22 <= _writeData_T_40;
        else
          regs_22 <= _writeData_T_42;
      end
      else
        regs_22 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h17)
        regs_23 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h17)) begin
        if (reset)
          regs_23 <= 32'h0;
      end
      else if (_GEN_24)
        regs_23 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_23 <= _GEN_15;
        else
          regs_23 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_23 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_23 <= _writeData_T_30;
              else if (_r1_T)
                regs_23 <= 32'h0;
              else
                regs_23 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_23 <= _writeData_T_34;
              else
                regs_23 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_23 <= _writeData_T_37;
              else if (_r1_T)
                regs_23 <= 32'h0;
              else
                regs_23 <= _GEN_0;
            end
            else
              regs_23 <= 32'h0;
          end
          else
            regs_23 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_23 <= _GEN_20;
        else if (instr[30])
          regs_23 <= _writeData_T_40;
        else
          regs_23 <= _writeData_T_42;
      end
      else
        regs_23 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h18)
        regs_24 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h18)) begin
        if (reset)
          regs_24 <= 32'h0;
      end
      else if (_GEN_24)
        regs_24 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_24 <= _GEN_15;
        else
          regs_24 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_24 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_24 <= _writeData_T_30;
              else if (_r1_T)
                regs_24 <= 32'h0;
              else
                regs_24 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_24 <= _writeData_T_34;
              else
                regs_24 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_24 <= _writeData_T_37;
              else if (_r1_T)
                regs_24 <= 32'h0;
              else
                regs_24 <= _GEN_0;
            end
            else
              regs_24 <= 32'h0;
          end
          else
            regs_24 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_24 <= _GEN_20;
        else if (instr[30])
          regs_24 <= _writeData_T_40;
        else
          regs_24 <= _writeData_T_42;
      end
      else
        regs_24 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h19)
        regs_25 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h19)) begin
        if (reset)
          regs_25 <= 32'h0;
      end
      else if (_GEN_24)
        regs_25 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_25 <= _GEN_15;
        else
          regs_25 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_25 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_25 <= _writeData_T_30;
              else if (_r1_T)
                regs_25 <= 32'h0;
              else
                regs_25 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_25 <= _writeData_T_34;
              else
                regs_25 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_25 <= _writeData_T_37;
              else if (_r1_T)
                regs_25 <= 32'h0;
              else
                regs_25 <= _GEN_0;
            end
            else
              regs_25 <= 32'h0;
          end
          else
            regs_25 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_25 <= _GEN_20;
        else if (instr[30])
          regs_25 <= _writeData_T_40;
        else
          regs_25 <= _writeData_T_42;
      end
      else
        regs_25 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h1A)
        regs_26 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h1A)) begin
        if (reset)
          regs_26 <= 32'h0;
      end
      else if (_GEN_24)
        regs_26 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_26 <= _GEN_15;
        else
          regs_26 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_26 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_26 <= _writeData_T_30;
              else if (_r1_T)
                regs_26 <= 32'h0;
              else
                regs_26 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_26 <= _writeData_T_34;
              else
                regs_26 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_26 <= _writeData_T_37;
              else if (_r1_T)
                regs_26 <= 32'h0;
              else
                regs_26 <= _GEN_0;
            end
            else
              regs_26 <= 32'h0;
          end
          else
            regs_26 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_26 <= _GEN_20;
        else if (instr[30])
          regs_26 <= _writeData_T_40;
        else
          regs_26 <= _writeData_T_42;
      end
      else
        regs_26 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h1B)
        regs_27 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h1B)) begin
        if (reset)
          regs_27 <= 32'h0;
      end
      else if (_GEN_24)
        regs_27 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_27 <= _GEN_15;
        else
          regs_27 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_27 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_27 <= _writeData_T_30;
              else if (_r1_T)
                regs_27 <= 32'h0;
              else
                regs_27 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_27 <= _writeData_T_34;
              else
                regs_27 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_27 <= _writeData_T_37;
              else if (_r1_T)
                regs_27 <= 32'h0;
              else
                regs_27 <= _GEN_0;
            end
            else
              regs_27 <= 32'h0;
          end
          else
            regs_27 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_27 <= _GEN_20;
        else if (instr[30])
          regs_27 <= _writeData_T_40;
        else
          regs_27 <= _writeData_T_42;
      end
      else
        regs_27 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h1C)
        regs_28 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h1C)) begin
        if (reset)
          regs_28 <= 32'h0;
      end
      else if (_GEN_24)
        regs_28 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_28 <= _GEN_15;
        else
          regs_28 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_28 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_28 <= _writeData_T_30;
              else if (_r1_T)
                regs_28 <= 32'h0;
              else
                regs_28 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_28 <= _writeData_T_34;
              else
                regs_28 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_28 <= _writeData_T_37;
              else if (_r1_T)
                regs_28 <= 32'h0;
              else
                regs_28 <= _GEN_0;
            end
            else
              regs_28 <= 32'h0;
          end
          else
            regs_28 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_28 <= _GEN_20;
        else if (instr[30])
          regs_28 <= _writeData_T_40;
        else
          regs_28 <= _writeData_T_42;
      end
      else
        regs_28 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h1D)
        regs_29 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h1D)) begin
        if (reset)
          regs_29 <= 32'h0;
      end
      else if (_GEN_24)
        regs_29 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_29 <= _GEN_15;
        else
          regs_29 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_29 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_29 <= _writeData_T_30;
              else if (_r1_T)
                regs_29 <= 32'h0;
              else
                regs_29 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_29 <= _writeData_T_34;
              else
                regs_29 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_29 <= _writeData_T_37;
              else if (_r1_T)
                regs_29 <= 32'h0;
              else
                regs_29 <= _GEN_0;
            end
            else
              regs_29 <= 32'h0;
          end
          else
            regs_29 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_29 <= _GEN_20;
        else if (instr[30])
          regs_29 <= _writeData_T_40;
        else
          regs_29 <= _writeData_T_42;
      end
      else
        regs_29 <= _GEN_23;
      if (_GEN_30 & (|memRd) & memRd == 5'h1E)
        regs_30 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & instr[11:7] == 5'h1E)) begin
        if (reset)
          regs_30 <= 32'h0;
      end
      else if (_GEN_24)
        regs_30 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_30 <= _GEN_15;
        else
          regs_30 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_30 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_30 <= _writeData_T_30;
              else if (_r1_T)
                regs_30 <= 32'h0;
              else
                regs_30 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_30 <= _writeData_T_34;
              else
                regs_30 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_30 <= _writeData_T_37;
              else if (_r1_T)
                regs_30 <= 32'h0;
              else
                regs_30 <= _GEN_0;
            end
            else
              regs_30 <= 32'h0;
          end
          else
            regs_30 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_30 <= _GEN_20;
        else if (instr[30])
          regs_30 <= _writeData_T_40;
        else
          regs_30 <= _writeData_T_42;
      end
      else
        regs_30 <= _GEN_23;
      if (_GEN_30 & (|memRd) & (&memRd))
        regs_31 <= narrowed;
      else if (~_GEN_1 | _GEN_28 | ~(_GEN_27 & (&(instr[11:7])))) begin
        if (reset)
          regs_31 <= 32'h0;
      end
      else if (_GEN_24)
        regs_31 <= alu;
      else if (_GEN_7) begin
        if (|(instr[14:12]))
          regs_31 <= _GEN_15;
        else
          regs_31 <= _writeData_T;
      end
      else if (_GEN_16) begin
        if (_GEN_17) begin
          if (|(instr[14:12])) begin
            if (_GEN_9)
              regs_31 <= _writeData_T_26;
            else if (_GEN_10) begin
              if (|r2)
                regs_31 <= _writeData_T_30;
              else if (_r1_T)
                regs_31 <= 32'h0;
              else
                regs_31 <= _GEN_0;
            end
            else if (_GEN_12) begin
              if (|r2)
                regs_31 <= _writeData_T_34;
              else
                regs_31 <= 32'hFFFFFFFF;
            end
            else if (&(instr[14:12])) begin
              if (|r2)
                regs_31 <= _writeData_T_37;
              else if (_r1_T)
                regs_31 <= 32'h0;
              else
                regs_31 <= _GEN_0;
            end
            else
              regs_31 <= 32'h0;
          end
          else
            regs_31 <= _writeData_T_19;
        end
        else if (|(instr[14:12]))
          regs_31 <= _GEN_20;
        else if (instr[30])
          regs_31 <= _writeData_T_40;
        else
          regs_31 <= _writeData_T_42;
      end
      else
        regs_31 <= _GEN_23;
      if (_GEN_31) begin
        pc <= pc + 32'h4;
        state <= 4'h0;
        commitRd <= 5'h0;
        commitData <= 32'h0;
      end
      else begin
        if (_GEN_30) begin
          pc <= nextPc;
          commitRd <= memRd;
          commitData <= narrowed;
        end
        else if (_GEN_29) begin
          if (reset)
            pc <= 32'h80000000;
        end
        else begin
          automatic logic       _GEN_33;
          automatic logic [7:0] _GEN_34;
          _GEN_33 = ~(|(instr[14:12])) & r1 == r2;
          _GEN_34 =
            {{r1 >= r2},
             {r1 < r2},
             {$signed(r1) >= $signed(r2)},
             {$signed(r1) < $signed(r2)},
             {_GEN_33},
             {_GEN_33},
             {r1 != r2},
             {_GEN_33}};
          if (~(_GEN_5 | _GEN_6 | _GEN_7 | _GEN_16)
              & (_GEN_21 | _GEN_22 | instr[6:0] == 7'h63 & _GEN_34[instr[14:12]])) begin
            if (instr[6:0] == 7'h6F)
              pc <= pc + {{12{instr[31]}}, instr[19:12], instr[20], instr[30:21], 1'h0};
            else if (instr[6:0] == 7'h67)
              pc <= r1 + _GEN_8 & 32'hFFFFFFFE;
            else
              pc <= pc + {{20{instr[31]}}, instr[7], instr[30:25], instr[11:8], 1'h0};
          end
          else
            pc <= _fallthrough_T;
          commitRd <= _GEN_27 ? instr[11:7] : 5'h0;
          commitData <=
            _GEN_27
              ? (_GEN_24
                   ? alu
                   : _GEN_7
                       ? ((|(instr[14:12])) ? _GEN_15 : _writeData_T)
                       : _GEN_16
                           ? (_GEN_17
                                ? ((|(instr[14:12]))
                                     ? (_GEN_9
                                          ? _writeData_T_26
                                          : _GEN_10
                                              ? ((|r2) ? _writeData_T_30 : r1)
                                              : _GEN_12
                                                  ? ((|r2)
                                                       ? _writeData_T_34
                                                       : 32'hFFFFFFFF)
                                                  : (&(instr[14:12]))
                                                      ? ((|r2) ? _writeData_T_37 : r1)
                                                      : 32'h0)
                                     : _writeData_T_19)
                                : (|(instr[14:12]))
                                    ? _GEN_20
                                    : instr[30] ? _writeData_T_40 : _writeData_T_42)
                           : _GEN_23)
              : 32'h0;
        end
        if (io_axi_w_valid_0 & io_axi_w_ready)
          state <= 4'h7;
        else if (io_axi_aw_valid_0 & io_axi_aw_ready)
          state <= 4'h6;
        else if (_GEN_30)
          state <= 4'h0;
        else begin
          automatic logic _GEN_35;
          _GEN_35 = io_axi_ar_ready & io_axi_ar_valid_0;
          if (_io_axi_ar_bits_addr_T & _GEN_35)
            state <= 4'h4;
          else if (_GEN_1)
            state <= _GEN_2 ? 4'h8 : isLoad ? 4'h3 : isStore ? 4'h5 : 4'h0;
          else if (_GEN_26)
            state <= 4'h2;
          else if (_io_axi_ar_valid_T & _GEN_35)
            state <= 4'h1;
          else if (reset)
            state <= 4'h0;
        end
      end
      if (_GEN_26)
        instr <= io_axi_r_bits_data;
      commitValid <= _GEN_32 | _GEN_1 & ~_GEN_4 & ~isStore;
      if (_GEN_32 | ~_GEN_29) begin
        commitPc <= pc;
        commitInstr <= instr;
      end
      commitWen <= ~_GEN_31 & (_GEN_30 ? (|memRd) : _GEN_29 ? commitWen : _GEN_27);
    end
    if (~_GEN_1 | _GEN_2 | ~_GEN_3) begin
    end
    else
      memAddr <= _effective_T_1;
    if (~_GEN_1 | _GEN_4 | ~isStore) begin
    end
    else begin
      automatic logic [94:0] _memWdata_T_2;
      automatic logic [4:0]  _memStrb_T_6;
      _memWdata_T_2 = {63'h0, r2} << {90'h0, _effective_T_1[1:0], 3'h0};
      memWdata <= _memWdata_T_2[31:0];
      _memStrb_T_6 = 5'h3 << {3'h0, _effective_T_1[1], 1'h0};
      memStrb <=
        (|(instr[14:12]))
          ? (instr[14:12] == 3'h1 ? _memStrb_T_6[3:0] : 4'hF)
          : 4'h1 << _effective_T_1[1:0];
    end
    if (~_GEN_1 | _GEN_2 | ~isLoad) begin
    end
    else begin
      memRd <= instr[11:7];
      memLoadSigned <= instr[14:12] != 3'h4 & instr[14:12] != 3'h5;
      memLoadSize <=
        ~(|(instr[14:12])) | instr[14:12] == 3'h4
          ? 2'h0
          : instr[14:12] == 3'h1 | instr[14:12] == 3'h5 ? 2'h1 : 2'h2;
      nextPc <= _fallthrough_T;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      automatic logic [31:0] _RANDOM[0:40];
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [5:0] i = 6'h0; i < 6'h29; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        regs_0 = _RANDOM[6'h0];
        regs_1 = _RANDOM[6'h1];
        regs_2 = _RANDOM[6'h2];
        regs_3 = _RANDOM[6'h3];
        regs_4 = _RANDOM[6'h4];
        regs_5 = _RANDOM[6'h5];
        regs_6 = _RANDOM[6'h6];
        regs_7 = _RANDOM[6'h7];
        regs_8 = _RANDOM[6'h8];
        regs_9 = _RANDOM[6'h9];
        regs_10 = _RANDOM[6'hA];
        regs_11 = _RANDOM[6'hB];
        regs_12 = _RANDOM[6'hC];
        regs_13 = _RANDOM[6'hD];
        regs_14 = _RANDOM[6'hE];
        regs_15 = _RANDOM[6'hF];
        regs_16 = _RANDOM[6'h10];
        regs_17 = _RANDOM[6'h11];
        regs_18 = _RANDOM[6'h12];
        regs_19 = _RANDOM[6'h13];
        regs_20 = _RANDOM[6'h14];
        regs_21 = _RANDOM[6'h15];
        regs_22 = _RANDOM[6'h16];
        regs_23 = _RANDOM[6'h17];
        regs_24 = _RANDOM[6'h18];
        regs_25 = _RANDOM[6'h19];
        regs_26 = _RANDOM[6'h1A];
        regs_27 = _RANDOM[6'h1B];
        regs_28 = _RANDOM[6'h1C];
        regs_29 = _RANDOM[6'h1D];
        regs_30 = _RANDOM[6'h1E];
        regs_31 = _RANDOM[6'h1F];
        pc = _RANDOM[6'h20];
        instr = _RANDOM[6'h21];
        memAddr = _RANDOM[6'h22];
        memWdata = _RANDOM[6'h23];
        memStrb = _RANDOM[6'h24][3:0];
        memRd = _RANDOM[6'h24][8:4];
        memLoadSigned = _RANDOM[6'h24][9];
        memLoadSize = _RANDOM[6'h24][11:10];
        nextPc = {_RANDOM[6'h24][31:13], _RANDOM[6'h25][12:0]};
        state = _RANDOM[6'h25][16:13];
        commitValid = _RANDOM[6'h25][17];
        commitPc = {_RANDOM[6'h25][31:18], _RANDOM[6'h26][17:0]};
        commitInstr = {_RANDOM[6'h26][31:18], _RANDOM[6'h27][17:0]};
        commitRd = _RANDOM[6'h27][22:18];
        commitData = {_RANDOM[6'h27][31:23], _RANDOM[6'h28][22:0]};
        commitWen = _RANDOM[6'h28][23];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_axi_ar_valid = io_axi_ar_valid_0;
  assign io_axi_ar_bits_addr = _io_axi_ar_bits_addr_T ? io_axi_aw_bits_addr_0 : pc;
  assign io_axi_r_ready = io_axi_r_ready_0;
  assign io_axi_aw_valid = io_axi_aw_valid_0;
  assign io_axi_aw_bits_addr = io_axi_aw_bits_addr_0;
  assign io_axi_w_valid = io_axi_w_valid_0;
  assign io_axi_w_bits_data = memWdata;
  assign io_axi_w_bits_strb = memStrb;
  assign io_axi_b_ready = io_axi_b_ready_0;
  assign io_debug_commit = commitValid;
  assign io_debug_pc = commitPc;
  assign io_debug_instr = commitInstr;
  assign io_debug_rd = commitRd;
  assign io_debug_wdata = commitData;
  assign io_debug_wen = commitWen;
  assign io_halted = state == 4'h8;
endmodule

module AxiCache(
  input         clock,
                reset,
  output        io_cpu_ar_ready,
  input         io_cpu_ar_valid,
  input  [31:0] io_cpu_ar_bits_addr,
  input         io_cpu_r_ready,
  output        io_cpu_r_valid,
  output [31:0] io_cpu_r_bits_data,
  output        io_cpu_aw_ready,
  input         io_cpu_aw_valid,
  input  [31:0] io_cpu_aw_bits_addr,
  output        io_cpu_w_ready,
  input         io_cpu_w_valid,
  input  [31:0] io_cpu_w_bits_data,
  input  [3:0]  io_cpu_w_bits_strb,
  input         io_cpu_b_ready,
  output        io_cpu_b_valid,
  input         io_mem_ar_ready,
  output        io_mem_ar_valid,
  output [31:0] io_mem_ar_bits_addr,
  output        io_mem_r_ready,
  input         io_mem_r_valid,
  input  [31:0] io_mem_r_bits_data,
  input         io_mem_aw_ready,
  output        io_mem_aw_valid,
  output [31:0] io_mem_aw_bits_addr,
  input         io_mem_w_ready,
  output        io_mem_w_valid,
  output [31:0] io_mem_w_bits_data,
  output [3:0]  io_mem_w_bits_strb,
  output        io_mem_b_ready,
  input         io_mem_b_valid
);

  reg              valid_0;
  reg              valid_1;
  reg              valid_2;
  reg              valid_3;
  reg  [27:0]      tags_0;
  reg  [27:0]      tags_1;
  reg  [27:0]      tags_2;
  reg  [27:0]      tags_3;
  reg  [31:0]      data_0;
  reg  [31:0]      data_1;
  reg  [31:0]      data_2;
  reg  [31:0]      data_3;
  reg              readPending;
  reg  [31:0]      readAddr;
  reg  [1:0]       readIndex;
  reg  [27:0]      readTag;
  reg  [2:0]       state;
  wire             _io_mem_w_valid_T = state == 3'h0;
  wire             io_cpu_ar_ready_0 = _io_mem_w_valid_T & ~readPending;
  wire             io_cpu_r_valid_0 = state == 3'h2;
  wire [3:0][31:0] _GEN = {{data_3}, {data_2}, {data_1}, {data_0}};
  wire             io_mem_r_ready_0 = state == 3'h1;
  always @(posedge clock) begin
    automatic logic _GEN_0;
    automatic logic _GEN_1;
    automatic logic _GEN_2;
    automatic logic _GEN_3;
    automatic logic _GEN_4;
    automatic logic _GEN_5;
    _GEN_0 = _io_mem_w_valid_T & io_cpu_ar_ready_0 & io_cpu_ar_valid;
    _GEN_1 = io_mem_r_ready_0 & io_mem_r_valid;
    _GEN_2 = _GEN_1 & readIndex == 2'h0;
    _GEN_3 = _GEN_1 & readIndex == 2'h1;
    _GEN_4 = _GEN_1 & readIndex == 2'h2;
    _GEN_5 = _GEN_1 & (&readIndex);
    if (reset) begin
      valid_0 <= 1'h0;
      valid_1 <= 1'h0;
      valid_2 <= 1'h0;
      valid_3 <= 1'h0;
      readPending <= 1'h0;
      state <= 3'h0;
    end
    else begin
      valid_0 <= ~io_cpu_aw_valid & (_GEN_2 | ~reset & valid_0);
      valid_1 <= ~io_cpu_aw_valid & (_GEN_3 | ~reset & valid_1);
      valid_2 <= ~io_cpu_aw_valid & (_GEN_4 | ~reset & valid_2);
      valid_3 <= ~io_cpu_aw_valid & (_GEN_5 | ~reset & valid_3);
      readPending <=
        ~_GEN_1 & (io_mem_r_ready_0 & io_mem_ar_ready | ~reset & readPending);
      if (io_cpu_r_valid_0 & io_cpu_r_ready)
        state <= 3'h0;
      else if (_GEN_1)
        state <= 3'h2;
      else if (_GEN_0) begin
        automatic logic [3:0]       _GEN_6;
        automatic logic [3:0][27:0] _GEN_7;
        _GEN_6 = {{valid_3}, {valid_2}, {valid_1}, {valid_0}};
        _GEN_7 = {{tags_3}, {tags_2}, {tags_1}, {tags_0}};
        state <=
          _GEN_6[io_cpu_ar_bits_addr[3:2]]
          & _GEN_7[io_cpu_ar_bits_addr[3:2]] == io_cpu_ar_bits_addr[31:4]
            ? 3'h2
            : 3'h1;
      end
      else if (reset)
        state <= 3'h0;
    end
    if (_GEN_2) begin
      tags_0 <= readTag;
      data_0 <= io_mem_r_bits_data;
    end
    if (_GEN_3) begin
      tags_1 <= readTag;
      data_1 <= io_mem_r_bits_data;
    end
    if (_GEN_4) begin
      tags_2 <= readTag;
      data_2 <= io_mem_r_bits_data;
    end
    if (_GEN_5) begin
      tags_3 <= readTag;
      data_3 <= io_mem_r_bits_data;
    end
    if (_GEN_0) begin
      readAddr <= io_cpu_ar_bits_addr;
      readIndex <= io_cpu_ar_bits_addr[3:2];
      readTag <= io_cpu_ar_bits_addr[31:4];
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      automatic logic [31:0] _RANDOM[0:9];
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'hA; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        valid_0 = _RANDOM[4'h0][0];
        valid_1 = _RANDOM[4'h0][1];
        valid_2 = _RANDOM[4'h0][2];
        valid_3 = _RANDOM[4'h0][3];
        tags_0 = _RANDOM[4'h0][31:4];
        tags_1 = _RANDOM[4'h1][27:0];
        tags_2 = {_RANDOM[4'h1][31:28], _RANDOM[4'h2][23:0]};
        tags_3 = {_RANDOM[4'h2][31:24], _RANDOM[4'h3][19:0]};
        data_0 = {_RANDOM[4'h3][31:20], _RANDOM[4'h4][19:0]};
        data_1 = {_RANDOM[4'h4][31:20], _RANDOM[4'h5][19:0]};
        data_2 = {_RANDOM[4'h5][31:20], _RANDOM[4'h6][19:0]};
        data_3 = {_RANDOM[4'h6][31:20], _RANDOM[4'h7][19:0]};
        readPending = _RANDOM[4'h7][20];
        readAddr = {_RANDOM[4'h7][31:21], _RANDOM[4'h8][20:0]};
        readIndex = _RANDOM[4'h8][26:25];
        readTag = {_RANDOM[4'h8][31:27], _RANDOM[4'h9][22:0]};
        state = _RANDOM[4'h9][25:23];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_cpu_ar_ready = io_cpu_ar_ready_0;
  assign io_cpu_r_valid = io_cpu_r_valid_0;
  assign io_cpu_r_bits_data = _GEN[readIndex];
  assign io_cpu_aw_ready = _io_mem_w_valid_T & io_mem_aw_ready;
  assign io_cpu_w_ready = _io_mem_w_valid_T & io_mem_w_ready;
  assign io_cpu_b_valid = io_mem_b_valid;
  assign io_mem_ar_valid = io_mem_r_ready_0;
  assign io_mem_ar_bits_addr = readAddr;
  assign io_mem_r_ready = io_mem_r_ready_0;
  assign io_mem_aw_valid = _io_mem_w_valid_T & io_cpu_aw_valid;
  assign io_mem_aw_bits_addr = io_cpu_aw_bits_addr;
  assign io_mem_w_valid = _io_mem_w_valid_T & io_cpu_w_valid;
  assign io_mem_w_bits_data = io_cpu_w_bits_data;
  assign io_mem_w_bits_strb = io_cpu_w_bits_strb;
  assign io_mem_b_ready = io_cpu_b_ready;
endmodule

module core_top(
  input         clock,
                reset,
                io_mei,
                io_msi,
                io_mti,
                io_sei,
                io_axi_ar_ready,
  output        io_axi_ar_valid,
  output [3:0]  io_axi_ar_bits_id,
  output [31:0] io_axi_ar_bits_addr,
  output [7:0]  io_axi_ar_bits_len,
  output [2:0]  io_axi_ar_bits_size,
  output [1:0]  io_axi_ar_bits_burst,
  output [2:0]  io_axi_ar_bits_prot,
  output        io_axi_r_ready,
  input         io_axi_r_valid,
  input  [3:0]  io_axi_r_bits_id,
  input  [31:0] io_axi_r_bits_data,
  input  [1:0]  io_axi_r_bits_resp,
  input         io_axi_r_bits_last,
                io_axi_aw_ready,
  output        io_axi_aw_valid,
  output [3:0]  io_axi_aw_bits_id,
  output [31:0] io_axi_aw_bits_addr,
  output [7:0]  io_axi_aw_bits_len,
  output [2:0]  io_axi_aw_bits_size,
  output [1:0]  io_axi_aw_bits_burst,
  output [2:0]  io_axi_aw_bits_prot,
  input         io_axi_w_ready,
  output        io_axi_w_valid,
  output [3:0]  io_axi_w_bits_id,
  output [31:0] io_axi_w_bits_data,
  output [3:0]  io_axi_w_bits_strb,
  output        io_axi_w_bits_last,
                io_axi_b_ready,
  input         io_axi_b_valid,
  input  [3:0]  io_axi_b_bits_id,
  input  [1:0]  io_axi_b_bits_resp,
  output        io_debug_commit,
  output [31:0] io_debug_pc,
                io_debug_instr,
  output [4:0]  io_debug_rf_wnum,
  output [31:0] io_debug_rf_wdata,
  output        io_debug_rf_wen,
                io_halted
);

  wire        _cache_io_cpu_ar_ready;
  wire        _cache_io_cpu_r_valid;
  wire [31:0] _cache_io_cpu_r_bits_data;
  wire        _cache_io_cpu_aw_ready;
  wire        _cache_io_cpu_w_ready;
  wire        _cache_io_cpu_b_valid;
  wire        _core_io_axi_ar_valid;
  wire [31:0] _core_io_axi_ar_bits_addr;
  wire        _core_io_axi_r_ready;
  wire        _core_io_axi_aw_valid;
  wire [31:0] _core_io_axi_aw_bits_addr;
  wire        _core_io_axi_w_valid;
  wire [31:0] _core_io_axi_w_bits_data;
  wire [3:0]  _core_io_axi_w_bits_strb;
  wire        _core_io_axi_b_ready;
  Core core (
    .clock               (clock),
    .reset               (reset),
    .io_axi_ar_ready     (_cache_io_cpu_ar_ready),
    .io_axi_ar_valid     (_core_io_axi_ar_valid),
    .io_axi_ar_bits_addr (_core_io_axi_ar_bits_addr),
    .io_axi_r_ready      (_core_io_axi_r_ready),
    .io_axi_r_valid      (_cache_io_cpu_r_valid),
    .io_axi_r_bits_data  (_cache_io_cpu_r_bits_data),
    .io_axi_aw_ready     (_cache_io_cpu_aw_ready),
    .io_axi_aw_valid     (_core_io_axi_aw_valid),
    .io_axi_aw_bits_addr (_core_io_axi_aw_bits_addr),
    .io_axi_w_ready      (_cache_io_cpu_w_ready),
    .io_axi_w_valid      (_core_io_axi_w_valid),
    .io_axi_w_bits_data  (_core_io_axi_w_bits_data),
    .io_axi_w_bits_strb  (_core_io_axi_w_bits_strb),
    .io_axi_b_ready      (_core_io_axi_b_ready),
    .io_axi_b_valid      (_cache_io_cpu_b_valid),
    .io_debug_commit     (io_debug_commit),
    .io_debug_pc         (io_debug_pc),
    .io_debug_instr      (io_debug_instr),
    .io_debug_rd         (io_debug_rf_wnum),
    .io_debug_wdata      (io_debug_rf_wdata),
    .io_debug_wen        (io_debug_rf_wen),
    .io_halted           (io_halted)
  );
  AxiCache cache (
    .clock               (clock),
    .reset               (reset),
    .io_cpu_ar_ready     (_cache_io_cpu_ar_ready),
    .io_cpu_ar_valid     (_core_io_axi_ar_valid),
    .io_cpu_ar_bits_addr (_core_io_axi_ar_bits_addr),
    .io_cpu_r_ready      (_core_io_axi_r_ready),
    .io_cpu_r_valid      (_cache_io_cpu_r_valid),
    .io_cpu_r_bits_data  (_cache_io_cpu_r_bits_data),
    .io_cpu_aw_ready     (_cache_io_cpu_aw_ready),
    .io_cpu_aw_valid     (_core_io_axi_aw_valid),
    .io_cpu_aw_bits_addr (_core_io_axi_aw_bits_addr),
    .io_cpu_w_ready      (_cache_io_cpu_w_ready),
    .io_cpu_w_valid      (_core_io_axi_w_valid),
    .io_cpu_w_bits_data  (_core_io_axi_w_bits_data),
    .io_cpu_w_bits_strb  (_core_io_axi_w_bits_strb),
    .io_cpu_b_ready      (_core_io_axi_b_ready),
    .io_cpu_b_valid      (_cache_io_cpu_b_valid),
    .io_mem_ar_ready     (io_axi_ar_ready),
    .io_mem_ar_valid     (io_axi_ar_valid),
    .io_mem_ar_bits_addr (io_axi_ar_bits_addr),
    .io_mem_r_ready      (io_axi_r_ready),
    .io_mem_r_valid      (io_axi_r_valid),
    .io_mem_r_bits_data  (io_axi_r_bits_data),
    .io_mem_aw_ready     (io_axi_aw_ready),
    .io_mem_aw_valid     (io_axi_aw_valid),
    .io_mem_aw_bits_addr (io_axi_aw_bits_addr),
    .io_mem_w_ready      (io_axi_w_ready),
    .io_mem_w_valid      (io_axi_w_valid),
    .io_mem_w_bits_data  (io_axi_w_bits_data),
    .io_mem_w_bits_strb  (io_axi_w_bits_strb),
    .io_mem_b_ready      (io_axi_b_ready),
    .io_mem_b_valid      (io_axi_b_valid)
  );
  assign io_axi_ar_bits_id = 4'h0;
  assign io_axi_ar_bits_len = 8'h0;
  assign io_axi_ar_bits_size = 3'h2;
  assign io_axi_ar_bits_burst = 2'h0;
  assign io_axi_ar_bits_prot = 3'h0;
  assign io_axi_aw_bits_id = 4'h1;
  assign io_axi_aw_bits_len = 8'h0;
  assign io_axi_aw_bits_size = 3'h2;
  assign io_axi_aw_bits_burst = 2'h0;
  assign io_axi_aw_bits_prot = 3'h0;
  assign io_axi_w_bits_id = 4'h1;
  assign io_axi_w_bits_last = 1'h1;
endmodule
