// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

module VectorCore(
  input        io_issue_valid,
  input  [2:0] io_issue_bits,
  output       io_write,
  output [2:0] io_writeVd
);

  assign io_write = io_issue_valid;
  assign io_writeVd = io_issue_bits;
endmodule

module CubeCore(
  input  clock,
         reset,
         io_launch,
  output io_launchReady,
         io_busy,
         io_done
);

  reg  [1:0] state;
  reg  [3:0] count;
  reg  [4:0] subCount;
  wire       io_launchReady_0 = state == 2'h0;
  wire       io_busy_0 = state == 2'h1;
  wire       io_done_0 = state == 2'h2;
  always @(posedge clock) begin
    if (reset) begin
      state <= 2'h0;
      count <= 4'h0;
      subCount <= 5'h0;
    end
    else begin
      automatic logic _GEN;
      _GEN = io_launchReady_0 & io_launch;
      if (io_done_0)
        state <= 2'h0;
      else if (io_busy_0 & (&subCount) & (&count))
        state <= 2'h2;
      else if (_GEN)
        state <= 2'h1;
      if (~(io_busy_0 & (&subCount)) | (&count)) begin
        if (_GEN)
          count <= 4'h0;
      end
      else
        count <= count + 4'h1;
      if (io_busy_0) begin
        if (&subCount)
          subCount <= 5'h0;
        else
          subCount <= subCount + 5'h1;
      end
      else if (_GEN)
        subCount <= 5'h0;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      automatic logic [31:0] _RANDOM[0:0];
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        state = _RANDOM[/*Zero width*/ 1'b0][1:0];
        count = _RANDOM[/*Zero width*/ 1'b0][5:2];
        subCount = _RANDOM[/*Zero width*/ 1'b0][10:6];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_launchReady = io_launchReady_0;
  assign io_busy = io_busy_0;
  assign io_done = io_done_0;
endmodule

module CubeCluster(
  input  clock,
         reset,
         io_launch,
  output io_launchReady,
         io_busy,
         io_done
);

  wire       _engines_5_io_launchReady;
  wire       _engines_5_io_busy;
  wire       _engines_5_io_done;
  wire       _engines_4_io_launchReady;
  wire       _engines_4_io_busy;
  wire       _engines_4_io_done;
  wire       _engines_3_io_launchReady;
  wire       _engines_3_io_busy;
  wire       _engines_3_io_done;
  wire       _engines_2_io_launchReady;
  wire       _engines_2_io_busy;
  wire       _engines_2_io_done;
  wire       _engines_1_io_launchReady;
  wire       _engines_1_io_busy;
  wire       _engines_1_io_done;
  wire       _engines_0_io_launchReady;
  wire       _engines_0_io_busy;
  wire       _engines_0_io_done;
  wire [5:0] selected_enc =
    _engines_0_io_launchReady
      ? 6'h1
      : _engines_1_io_launchReady
          ? 6'h2
          : _engines_2_io_launchReady
              ? 6'h4
              : _engines_3_io_launchReady
                  ? 6'h8
                  : _engines_4_io_launchReady ? 6'h10 : {_engines_5_io_launchReady, 5'h0};
  CubeCore engines_0 (
    .clock          (clock),
    .reset          (reset),
    .io_launch      (io_launch & selected_enc[0]),
    .io_launchReady (_engines_0_io_launchReady),
    .io_busy        (_engines_0_io_busy),
    .io_done        (_engines_0_io_done)
  );
  CubeCore engines_1 (
    .clock          (clock),
    .reset          (reset),
    .io_launch      (io_launch & selected_enc[1]),
    .io_launchReady (_engines_1_io_launchReady),
    .io_busy        (_engines_1_io_busy),
    .io_done        (_engines_1_io_done)
  );
  CubeCore engines_2 (
    .clock          (clock),
    .reset          (reset),
    .io_launch      (io_launch & selected_enc[2]),
    .io_launchReady (_engines_2_io_launchReady),
    .io_busy        (_engines_2_io_busy),
    .io_done        (_engines_2_io_done)
  );
  CubeCore engines_3 (
    .clock          (clock),
    .reset          (reset),
    .io_launch      (io_launch & selected_enc[3]),
    .io_launchReady (_engines_3_io_launchReady),
    .io_busy        (_engines_3_io_busy),
    .io_done        (_engines_3_io_done)
  );
  CubeCore engines_4 (
    .clock          (clock),
    .reset          (reset),
    .io_launch      (io_launch & selected_enc[4]),
    .io_launchReady (_engines_4_io_launchReady),
    .io_busy        (_engines_4_io_busy),
    .io_done        (_engines_4_io_done)
  );
  CubeCore engines_5 (
    .clock          (clock),
    .reset          (reset),
    .io_launch      (io_launch & selected_enc[5]),
    .io_launchReady (_engines_5_io_launchReady),
    .io_busy        (_engines_5_io_busy),
    .io_done        (_engines_5_io_done)
  );
  assign io_launchReady =
    |{_engines_5_io_launchReady,
      _engines_4_io_launchReady,
      _engines_3_io_launchReady,
      _engines_2_io_launchReady,
      _engines_1_io_launchReady,
      _engines_0_io_launchReady};
  assign io_busy =
    _engines_0_io_busy | _engines_1_io_busy | _engines_2_io_busy | _engines_3_io_busy
    | _engines_4_io_busy | _engines_5_io_busy;
  assign io_done =
    _engines_0_io_done | _engines_1_io_done | _engines_2_io_done | _engines_3_io_done
    | _engines_4_io_done | _engines_5_io_done;
endmodule

module Core(
  input         clock,
                reset,
                io_axi_ar_ready,
  output        io_axi_ar_valid,
  output [31:0] io_axi_ar_bits_addr,
  output        io_axi_r_ready,
  input         io_axi_r_valid,
  input  [3:0]  io_axi_r_bits_id,
  input  [31:0] io_axi_r_bits_data,
  input  [1:0]  io_axi_r_bits_resp,
  input         io_axi_r_bits_last,
                io_axi_aw_ready,
  output        io_axi_aw_valid,
  output [31:0] io_axi_aw_bits_addr,
  input         io_axi_w_ready,
  output        io_axi_w_valid,
  output [31:0] io_axi_w_bits_data,
  output [3:0]  io_axi_w_bits_strb,
  output        io_axi_b_ready,
  input         io_axi_b_valid,
  input  [3:0]  io_axi_b_bits_id,
  input  [1:0]  io_axi_b_bits_resp,
  output        io_debug_commit,
  output [31:0] io_debug_pc,
                io_debug_instr,
  output [4:0]  io_debug_rd,
  output [31:0] io_debug_wdata,
  output        io_debug_wen,
                io_debug_illegal,
                io_debug_vector_issue,
                io_debug_vector_write,
  output [2:0]  io_debug_vector_vd,
  output        io_debug_cube_launch,
                io_debug_cube_busy,
                io_debug_cube_done,
                io_debug_cube_wait_stall,
  output [3:0]  io_debug_stall_reason,
  output        io_halted
);

  wire        _cubeCore_io_launchReady;
  wire        _cubeCore_io_busy;
  reg  [31:0] regs_0;
  reg  [31:0] regs_1;
  reg  [31:0] regs_2;
  reg  [31:0] regs_3;
  reg  [31:0] regs_4;
  reg  [31:0] regs_5;
  reg  [31:0] regs_6;
  reg  [31:0] regs_7;
  reg  [31:0] regs_8;
  reg  [31:0] regs_9;
  reg  [31:0] regs_10;
  reg  [31:0] regs_11;
  reg  [31:0] regs_12;
  reg  [31:0] regs_13;
  reg  [31:0] regs_14;
  reg  [31:0] regs_15;
  reg  [31:0] regs_16;
  reg  [31:0] regs_17;
  reg  [31:0] regs_18;
  reg  [31:0] regs_19;
  reg  [31:0] regs_20;
  reg  [31:0] regs_21;
  reg  [31:0] regs_22;
  reg  [31:0] regs_23;
  reg  [31:0] regs_24;
  reg  [31:0] regs_25;
  reg  [31:0] regs_26;
  reg  [31:0] regs_27;
  reg  [31:0] regs_28;
  reg  [31:0] regs_29;
  reg  [31:0] regs_30;
  reg  [31:0] regs_31;
  reg  [31:0] pc;
  reg         ifid_valid;
  reg  [31:0] ifid_pc;
  reg  [31:0] ifid_instr;
  reg         idex_valid;
  reg  [31:0] idex_pc;
  reg  [31:0] idex_instr;
  reg  [4:0]  idex_rs1;
  reg  [4:0]  idex_rs2;
  reg  [4:0]  idex_rd;
  reg  [31:0] idex_rs1Data;
  reg  [31:0] idex_rs2Data;
  reg  [31:0] idex_immediate;
  reg         idex_control_regWrite;
  reg         idex_control_memRead;
  reg         idex_control_memWrite;
  reg         idex_control_memToReg;
  reg         idex_control_branch;
  reg         idex_control_jump;
  reg  [3:0]  idex_control_aluOp;
  reg         idex_control_aluSrcImmediate;
  reg  [1:0]  idex_control_loadSize;
  reg         idex_control_loadSigned;
  reg  [1:0]  idex_control_storeSize;
  reg         idex_control_writeUpperImmediate;
  reg         idex_control_writePcRelative;
  reg         idex_control_illegal;
  reg         idex_control_isVector;
  reg         idex_control_isCubeLaunch;
  reg         idex_control_isCubeWait;
  reg         exmem_valid;
  reg  [31:0] exmem_pc;
  reg  [31:0] exmem_instr;
  reg  [4:0]  exmem_rd;
  reg  [31:0] exmem_aluResult;
  reg         exmem_control_regWrite;
  reg         exmem_control_memRead;
  reg         exmem_control_memWrite;
  reg         exmem_control_memToReg;
  reg         memwb_valid;
  reg  [31:0] memwb_pc;
  reg  [31:0] memwb_instr;
  reg  [4:0]  memwb_rd;
  reg  [31:0] memwb_aluResult;
  reg  [31:0] memwb_loadData;
  reg         memwb_control_regWrite;
  reg         memwb_control_memToReg;
  reg  [2:0]  owner;
  reg  [31:0] memAddr;
  reg  [31:0] memData;
  reg  [3:0]  memStrb;
  reg  [4:0]  memRd;
  reg  [31:0] memPc;
  reg  [31:0] memInstr;
  reg  [1:0]  memSize;
  reg         memSigned;
  reg         draining;
  reg         halted;
  reg         illegalSeen;
  wire        _idUsesRs1_T = ifid_instr[6:0] == 7'h13;
  wire        _idUsesRs2_T = ifid_instr[6:0] == 7'h33;
  wire        _idUsesRs1_T_3 = ifid_instr[6:0] == 7'h3;
  wire        _idUsesRs2_T_1 = ifid_instr[6:0] == 7'h23;
  wire        _idUsesRs2_T_3 = ifid_instr[6:0] == 7'h63;
  wire        _idUsesRs1_T_9 = ifid_instr[6:0] == 7'h67;
  wire        loadUse =
    ifid_valid & idex_valid & idex_control_memRead & (|idex_rd)
    & ((_idUsesRs1_T | _idUsesRs2_T | _idUsesRs1_T_3 | _idUsesRs2_T_1 | _idUsesRs2_T_3
        | _idUsesRs1_T_9) & idex_rd == ifid_instr[19:15]
       | (_idUsesRs2_T | _idUsesRs2_T_1 | _idUsesRs2_T_3) & idex_rd == ifid_instr[24:20]);
  wire [31:0] wbValue = memwb_control_memToReg ? memwb_loadData : memwb_aluResult;
  wire        _d2_T = exmem_valid & exmem_control_regWrite;
  wire        _d2_T_7 = memwb_valid & memwb_control_regWrite;
  wire [31:0] exRs1 =
    idex_rs1 == 5'h0
      ? 32'h0
      : _d2_T & ~exmem_control_memRead & exmem_rd == idex_rs1
          ? exmem_aluResult
          : _d2_T_7 & memwb_rd == idex_rs1 ? wbValue : idex_rs1Data;
  wire [31:0] exRs2 =
    idex_rs2 == 5'h0
      ? 32'h0
      : _d2_T & ~exmem_control_memRead & exmem_rd == idex_rs2
          ? exmem_aluResult
          : _d2_T_7 & memwb_rd == idex_rs2 ? wbValue : idex_rs2Data;
  wire        _launchMem_T_1 = idex_control_memRead | idex_control_memWrite;
  wire        _cond_T_12 = idex_instr[14:12] == 3'h0 & exRs1 == exRs2;
  wire [7:0]  _GEN =
    {{exRs1 >= exRs2},
     {exRs1 < exRs2},
     {$signed(exRs1) >= $signed(exRs2)},
     {$signed(exRs1) < $signed(exRs2)},
     {_cond_T_12},
     {_cond_T_12},
     {exRs1 != exRs2},
     {_cond_T_12}};
  wire        taken =
    idex_valid & (idex_control_jump | idex_control_branch & _GEN[idex_instr[14:12]]);
  wire        canPipe =
    ~halted & ~((|owner) | exmem_valid & (exmem_control_memRead | exmem_control_memWrite))
    & ~draining;
  wire        _cubeCore_io_launch_T = canPipe & idex_valid;
  wire        launchMem = _cubeCore_io_launch_T & _launchMem_T_1;
  wire        cubeLaunchBlocked =
    idex_valid & idex_control_isCubeLaunch & ~_cubeCore_io_launchReady;
  wire        cubeWaitStall = idex_valid & idex_control_isCubeWait & _cubeCore_io_busy;
  wire        customBlocked = cubeLaunchBlocked | cubeWaitStall;
  wire        io_debug_vector_issue_0 =
    _cubeCore_io_launch_T & idex_control_isVector & ~customBlocked;
  wire        _cubeCore_io_launch_T_3 =
    _cubeCore_io_launch_T & idex_control_isCubeLaunch & ~customBlocked;
  wire        _io_axi_ar_bits_addr_T = owner == 3'h2;
  wire        _io_axi_ar_valid_T_1 = owner == 3'h0;
  wire        io_axi_ar_valid_0 =
    _io_axi_ar_bits_addr_T | _io_axi_ar_valid_T_1 & canPipe & ~customBlocked & ~launchMem
    & ~taken;
  wire [31:0] io_axi_aw_bits_addr_0 = memAddr & 32'hFFFFFFFC;
  wire        _fetchResponse_T = owner == 3'h1;
  wire        _io_axi_r_ready_T_3 = owner == 3'h3;
  wire        io_axi_r_ready_0 = _fetchResponse_T & ~customBlocked | _io_axi_r_ready_T_3;
  wire        io_axi_aw_valid_0 = owner == 3'h4;
  wire        io_axi_w_valid_0 = owner == 3'h5;
  wire        io_axi_b_ready_0 = owner == 3'h6;
  wire        _GEN_0 = idex_valid & idex_control_illegal;
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if ((`PRINTF_COND_) & _GEN_0 & ~reset)
        $fwrite(32'h80000002, "ILLEGAL instruction %x at %x\n", idex_instr, idex_pc);
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin
    automatic logic [31:0]      exOp2;
    automatic logic [31:0]      absRs1 = exRs1[31] ? 32'h0 - exRs1 : exRs1;
    automatic logic [31:0]      absRs2 = exRs2[31] ? 32'h0 - exRs2 : exRs2;
    automatic logic             _exResult_T_25 = exRs2 == 32'h0;
    automatic logic             _exResult_T_14 = exRs1 == 32'h80000000;
    automatic logic [31:0]      _signedDiv_T_10 = absRs1 / absRs2;
    automatic logic [63:0]      _GEN_1 = {32'h0, exRs2};
    automatic logic [63:0]      mulUU = {32'h0, exRs1} * _GEN_1;
    automatic logic [63:0]      _GEN_2 = {32'h0, absRs1};
    automatic logic [63:0]      mulAbs = _GEN_2 * {32'h0, absRs2};
    automatic logic [63:0]      _mulSU_T_4 = _GEN_2 * _GEN_1;
    automatic logic [31:0]      _exResult_T;
    automatic logic [31:0]      _exResult_T_2;
    automatic logic [31:0]      _exResult_T_4;
    automatic logic             _GEN_3;
    automatic logic [31:0]      _exResult_T_21 = absRs1 % absRs2;
    automatic logic [63:0]      _mulSU_T_3 = 64'h0 - _mulSU_T_4;
    automatic logic [63:0]      _mulSS_T_4 = 64'h0 - mulAbs;
    automatic logic [7:0][31:0] _GEN_4 =
      {{_exResult_T_25 ? exRs1 : exRs1 - exRs1 / exRs2 * exRs2},
       {_exResult_T_25
          ? exRs1
          : _exResult_T_14 & (&exRs2)
              ? 32'h0
              : exRs1[31] ? 32'h0 - _exResult_T_21 : _exResult_T_21},
       {_exResult_T_25 ? 32'hFFFFFFFF : exRs1 / exRs2},
       {_exResult_T_25
          ? 32'hFFFFFFFF
          : _exResult_T_14 & (&exRs2)
              ? 32'h80000000
              : exRs1[31] ^ exRs2[31] ? 32'h0 - _signedDiv_T_10 : _signedDiv_T_10},
       {mulUU[63:32]},
       {exRs1[31] ? _mulSU_T_3[63:32] : _mulSU_T_4[63:32]},
       {exRs1[31] ^ exRs2[31] ? _mulSS_T_4[63:32] : mulAbs[63:32]},
       {mulUU[31:0]}};
    automatic logic [31:0]      _GEN_5;
    automatic logic [31:0]      _GEN_6;
    automatic logic [62:0]      _exResult_T_41;
    automatic logic [7:0][31:0] _GEN_7;
    automatic logic [31:0]      _GEN_8;
    automatic logic             _GEN_9;
    automatic logic             _GEN_10;
    exOp2 = idex_control_aluSrcImmediate ? idex_immediate : exRs2;
    _exResult_T = exRs1 + idex_immediate;
    _exResult_T_2 = idex_pc + idex_immediate;
    _exResult_T_4 = idex_pc + 32'h4;
    _GEN_3 = idex_control_aluOp == 4'h5;
    _GEN_5 = _GEN_4[idex_instr[14:12]];
    _GEN_6 = {27'h0, exOp2[4:0]};
    _exResult_T_41 = {31'h0, exRs1} << exOp2[4:0];
    _GEN_7 =
      {{exRs1 & exOp2},
       {exRs1 | exOp2},
       {idex_instr[30] ? $signed($signed(exRs1) >>> _GEN_6) : exRs1 >> _GEN_6},
       {exRs1 ^ exOp2},
       {{31'h0, exRs1 < exOp2}},
       {{31'h0, $signed(exRs1) < $signed(exOp2)}},
       {_exResult_T_41[31:0]},
       {idex_instr[6:0] == 7'h33 & idex_instr[30] ? exRs1 - exOp2 : exRs1 + exOp2}};
    _GEN_8 = _GEN_7[idex_instr[14:12]];
    _GEN_9 =
      idex_valid & ~idex_control_illegal & ~customBlocked & idex_instr != 32'h100073;
    _GEN_10 = canPipe & _GEN_9 & _launchMem_T_1;
    if (reset) begin
      regs_0 <= 32'h0;
      regs_1 <= 32'h0;
      regs_2 <= 32'h0;
      regs_3 <= 32'h0;
      regs_4 <= 32'h0;
      regs_5 <= 32'h0;
      regs_6 <= 32'h0;
      regs_7 <= 32'h0;
      regs_8 <= 32'h0;
      regs_9 <= 32'h0;
      regs_10 <= 32'h0;
      regs_11 <= 32'h0;
      regs_12 <= 32'h0;
      regs_13 <= 32'h0;
      regs_14 <= 32'h0;
      regs_15 <= 32'h0;
      regs_16 <= 32'h0;
      regs_17 <= 32'h0;
      regs_18 <= 32'h0;
      regs_19 <= 32'h0;
      regs_20 <= 32'h0;
      regs_21 <= 32'h0;
      regs_22 <= 32'h0;
      regs_23 <= 32'h0;
      regs_24 <= 32'h0;
      regs_25 <= 32'h0;
      regs_26 <= 32'h0;
      regs_27 <= 32'h0;
      regs_28 <= 32'h0;
      regs_29 <= 32'h0;
      regs_30 <= 32'h0;
      regs_31 <= 32'h0;
      pc <= 32'h80000000;
      ifid_valid <= 1'h0;
      ifid_pc <= 32'h0;
      ifid_instr <= 32'h0;
      idex_valid <= 1'h0;
      idex_pc <= 32'h0;
      idex_instr <= 32'h0;
      idex_rs1 <= 5'h0;
      idex_rs2 <= 5'h0;
      idex_rd <= 5'h0;
      idex_rs1Data <= 32'h0;
      idex_rs2Data <= 32'h0;
      idex_immediate <= 32'h0;
      idex_control_regWrite <= 1'h0;
      idex_control_memRead <= 1'h0;
      idex_control_memWrite <= 1'h0;
      idex_control_memToReg <= 1'h0;
      idex_control_branch <= 1'h0;
      idex_control_jump <= 1'h0;
      idex_control_aluOp <= 4'h0;
      idex_control_aluSrcImmediate <= 1'h0;
      idex_control_loadSize <= 2'h0;
      idex_control_loadSigned <= 1'h0;
      idex_control_storeSize <= 2'h0;
      idex_control_writeUpperImmediate <= 1'h0;
      idex_control_writePcRelative <= 1'h0;
      idex_control_illegal <= 1'h0;
      idex_control_isVector <= 1'h0;
      idex_control_isCubeLaunch <= 1'h0;
      idex_control_isCubeWait <= 1'h0;
      exmem_valid <= 1'h0;
      exmem_pc <= 32'h0;
      exmem_instr <= 32'h0;
      exmem_rd <= 5'h0;
      exmem_aluResult <= 32'h0;
      exmem_control_regWrite <= 1'h0;
      exmem_control_memRead <= 1'h0;
      exmem_control_memWrite <= 1'h0;
      exmem_control_memToReg <= 1'h0;
      memwb_valid <= 1'h0;
      memwb_pc <= 32'h0;
      memwb_instr <= 32'h0;
      memwb_rd <= 5'h0;
      memwb_aluResult <= 32'h0;
      memwb_loadData <= 32'h0;
      memwb_control_regWrite <= 1'h0;
      memwb_control_memToReg <= 1'h0;
      owner <= 3'h0;
      draining <= 1'h0;
      halted <= 1'h0;
      illegalSeen <= 1'h0;
    end
    else begin
      automatic logic _GEN_11;
      automatic logic _fetchResponse_T_1 = io_axi_r_ready_0 & io_axi_r_valid;
      automatic logic fetchResponse;
      automatic logic _GEN_12 =
        io_axi_r_bits_id == 4'h0 & io_axi_r_bits_resp == 2'h0 & io_axi_r_bits_last;
      automatic logic _GEN_13;
      automatic logic _GEN_14;
      automatic logic _GEN_15;
      automatic logic _GEN_16;
      automatic logic _GEN_17;
      automatic logic _GEN_18;
      automatic logic _GEN_19;
      automatic logic _GEN_20;
      automatic logic _GEN_21;
      automatic logic _GEN_22;
      automatic logic _GEN_23;
      automatic logic _GEN_24;
      automatic logic _GEN_25 = loadUse | taken;
      automatic logic ebreakSeen;
      automatic logic _GEN_26;
      automatic logic _GEN_27;
      _GEN_11 = memwb_control_regWrite & (|memwb_rd);
      fetchResponse = _fetchResponse_T & _fetchResponse_T_1;
      _GEN_13 = fetchResponse & _GEN_12 & ~draining;
      _GEN_14 = fetchResponse & ~_GEN_12;
      _GEN_15 = _io_axi_r_ready_T_3 & _fetchResponse_T_1;
      _GEN_16 = _GEN_15 & _GEN_12;
      _GEN_17 = _GEN_15 & _GEN_12;
      _GEN_18 = _GEN_15 & ~_GEN_12;
      _GEN_19 = io_axi_b_ready_0 & io_axi_b_valid;
      _GEN_20 = io_axi_b_bits_id == 4'h1 & io_axi_b_bits_resp == 2'h0;
      _GEN_21 = _GEN_19 & _GEN_20;
      _GEN_22 = _GEN_19 & ~_GEN_20;
      _GEN_23 = exmem_valid & ~exmem_control_memRead & ~exmem_control_memWrite;
      _GEN_24 = launchMem | customBlocked | loadUse;
      ebreakSeen = idex_valid & idex_instr == 32'h100073;
      _GEN_26 = ebreakSeen | _GEN_0;
      _GEN_27 =
        (draining | ebreakSeen) & exmem_valid & ~exmem_control_memRead
        & ~exmem_control_memWrite;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h0)
        regs_0 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h1)
        regs_1 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h2)
        regs_2 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h3)
        regs_3 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h4)
        regs_4 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h5)
        regs_5 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h6)
        regs_6 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h7)
        regs_7 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h8)
        regs_8 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h9)
        regs_9 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'hA)
        regs_10 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'hB)
        regs_11 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'hC)
        regs_12 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'hD)
        regs_13 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'hE)
        regs_14 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'hF)
        regs_15 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h10)
        regs_16 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h11)
        regs_17 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h12)
        regs_18 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h13)
        regs_19 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h14)
        regs_20 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h15)
        regs_21 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h16)
        regs_22 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h17)
        regs_23 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h18)
        regs_24 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h19)
        regs_25 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h1A)
        regs_26 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h1B)
        regs_27 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h1C)
        regs_28 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h1D)
        regs_29 <= wbValue;
      if (memwb_valid & _GEN_11 & memwb_rd == 5'h1E)
        regs_30 <= wbValue;
      if (memwb_valid & _GEN_11 & (&memwb_rd))
        regs_31 <= wbValue;
      if (_GEN_26)
        pc <= idex_pc;
      else if (~canPipe | _GEN_24 | ~taken) begin
        if (_GEN_13)
          pc <= pc + 32'h4;
      end
      else
        pc <=
          idex_control_jump & idex_instr[6:0] == 7'h67
            ? exRs1 + idex_immediate & 32'hFFFFFFFE
            : idex_pc + idex_immediate;
      ifid_valid <=
        ~_GEN_26 & (~canPipe | _GEN_24 | ~(taken | ~fetchResponse))
        & (_GEN_13 | ifid_valid);
      if (_GEN_13) begin
        ifid_pc <= pc;
        ifid_instr <= io_axi_r_bits_data;
      end
      idex_valid <=
        ~_GEN_26
        & (canPipe
             ? ~launchMem & (customBlocked ? idex_valid : ~_GEN_25 & ifid_valid)
             : idex_valid);
      if (~canPipe | launchMem | customBlocked | _GEN_25) begin
      end
      else begin
        automatic logic [31:0]       iimm;
        automatic logic              _scalarLegalFunct_T;
        automatic logic              _scalarLegalFunct_T_4;
        automatic logic              _idCustomIllegal_T;
        automatic logic              _idCustomIllegal_T_1;
        automatic logic              _idCtrl_storeSize_T_1;
        automatic logic              _scalarLegalFunct_T_19;
        automatic logic              _idCtrl_loadSigned_T_1;
        automatic logic              _scalarLegalFunct_T_22;
        automatic logic              _idCtrl_aluOp_T;
        automatic logic              _idCtrl_loadSize_T_4;
        automatic logic              _idCtrl_loadSize_T_1;
        automatic logic              _idCtrl_isCubeWait_T;
        automatic logic              idCtrl_writeUpperImmediate;
        automatic logic              _GEN_28;
        automatic logic              _GEN_29;
        automatic logic              _GEN_30;
        automatic logic              _GEN_31;
        automatic logic              _GEN_32;
        automatic logic              _GEN_33;
        automatic logic              idCtrl_memRead;
        automatic logic              _GEN_34;
        automatic logic              _GEN_35;
        automatic logic              _GEN_36;
        automatic logic              _GEN_37;
        automatic logic              _GEN_38;
        automatic logic              _GEN_39;
        automatic logic              _GEN_40;
        automatic logic              _GEN_41;
        automatic logic              _GEN_42;
        automatic logic              _GEN_43;
        automatic logic              _GEN_44;
        automatic logic [31:0][31:0] _GEN_45;
        iimm = {{20{ifid_instr[31]}}, ifid_instr[31:20]};
        _scalarLegalFunct_T = ifid_instr[6:0] == 7'hF;
        _scalarLegalFunct_T_4 = ifid_instr[6:0] == 7'h73;
        _idCustomIllegal_T = ifid_instr[6:0] == 7'hB;
        _idCustomIllegal_T_1 = ifid_instr[6:0] == 7'h2B;
        _idCtrl_storeSize_T_1 = ifid_instr[14:12] == 3'h1;
        _scalarLegalFunct_T_19 = ifid_instr[31:25] == 7'h0;
        _idCtrl_loadSigned_T_1 = ifid_instr[14:12] != 3'h5;
        _scalarLegalFunct_T_22 = ifid_instr[31:25] == 7'h20;
        _idCtrl_aluOp_T = ifid_instr[31:25] == 7'h1;
        _idCtrl_loadSize_T_4 = ifid_instr[14:12] == 3'h5;
        _idCtrl_loadSize_T_1 = ifid_instr[14:12] == 3'h4;
        _idCtrl_isCubeWait_T = ifid_instr[14:12] == 3'h1;
        idCtrl_writeUpperImmediate = ifid_instr[6:0] == 7'h37;
        _GEN_28 = ifid_instr[6:0] == 7'h17;
        _GEN_29 = ifid_instr[6:0] == 7'h13;
        _GEN_30 = ifid_instr[6:0] == 7'h33;
        _GEN_31 = _GEN_28 | _GEN_29;
        _GEN_32 = ifid_instr[6:0] == 7'h3;
        _GEN_33 = idCtrl_writeUpperImmediate | _GEN_28 | _GEN_29 | _GEN_30;
        idCtrl_memRead = ~_GEN_33 & _GEN_32;
        _GEN_34 = ifid_instr[6:0] == 7'h23;
        _GEN_35 = idCtrl_writeUpperImmediate | _GEN_28 | _GEN_29 | _GEN_30 | _GEN_32;
        _GEN_36 = ifid_instr[6:0] == 7'h63;
        _GEN_37 = _GEN_32 | _GEN_34;
        _GEN_38 = ifid_instr[6:0] == 7'h6F;
        _GEN_39 = ifid_instr[6:0] == 7'h67;
        _GEN_40 = _GEN_38 | _GEN_39;
        _GEN_41 = _GEN_34 | _GEN_36;
        _GEN_42 = ifid_instr[6:0] == 7'hB;
        _GEN_43 = ifid_instr[6:0] == 7'h2B;
        _GEN_44 =
          idCtrl_writeUpperImmediate | _GEN_28 | _GEN_29 | _GEN_30 | _GEN_32 | _GEN_34
          | _GEN_36 | _GEN_38 | _GEN_39 | _GEN_42;
        _GEN_45 =
          {{regs_31},
           {regs_30},
           {regs_29},
           {regs_28},
           {regs_27},
           {regs_26},
           {regs_25},
           {regs_24},
           {regs_23},
           {regs_22},
           {regs_21},
           {regs_20},
           {regs_19},
           {regs_18},
           {regs_17},
           {regs_16},
           {regs_15},
           {regs_14},
           {regs_13},
           {regs_12},
           {regs_11},
           {regs_10},
           {regs_9},
           {regs_8},
           {regs_7},
           {regs_6},
           {regs_5},
           {regs_4},
           {regs_3},
           {regs_2},
           {regs_1},
           {regs_0}};
        idex_pc <= ifid_pc;
        idex_instr <= ifid_instr;
        idex_rs1 <= ifid_instr[19:15];
        idex_rs2 <= ifid_instr[24:20];
        idex_rd <= ifid_instr[11:7];
        idex_rs1Data <=
          _d2_T & ~exmem_control_memRead & (|exmem_rd) & exmem_rd == ifid_instr[19:15]
            ? exmem_aluResult
            : _d2_T_7 & (|memwb_rd) & memwb_rd == ifid_instr[19:15]
                ? wbValue
                : ifid_instr[19:15] == 5'h0 ? 32'h0 : _GEN_45[ifid_instr[19:15]];
        idex_rs2Data <=
          _d2_T & ~exmem_control_memRead & (|exmem_rd) & exmem_rd == ifid_instr[24:20]
            ? exmem_aluResult
            : _d2_T_7 & (|memwb_rd) & memwb_rd == ifid_instr[24:20]
                ? wbValue
                : ifid_instr[24:20] == 5'h0 ? 32'h0 : _GEN_45[ifid_instr[24:20]];
        idex_immediate <=
          idCtrl_writeUpperImmediate | _GEN_28
            ? {ifid_instr[31:12], 12'h0}
            : _GEN_29
                ? iimm
                : _GEN_30
                    ? 32'h0
                    : _GEN_32
                        ? iimm
                        : _GEN_34
                            ? {{20{ifid_instr[31]}}, ifid_instr[31:25], ifid_instr[11:7]}
                            : _GEN_36
                                ? {{20{ifid_instr[31]}},
                                   ifid_instr[7],
                                   ifid_instr[30:25],
                                   ifid_instr[11:8],
                                   1'h0}
                                : _GEN_38
                                    ? {{12{ifid_instr[31]}},
                                       ifid_instr[19:12],
                                       ifid_instr[20],
                                       ifid_instr[30:21],
                                       1'h0}
                                    : _GEN_39 ? iimm : 32'h0;
        idex_control_regWrite <= _GEN_35 | ~_GEN_41 & _GEN_40;
        idex_control_memRead <= idCtrl_memRead;
        idex_control_memWrite <= ~_GEN_35 & _GEN_34;
        idex_control_memToReg <= idCtrl_memRead;
        idex_control_branch <=
          ~(idCtrl_writeUpperImmediate | _GEN_28 | _GEN_29 | _GEN_30 | _GEN_37) & _GEN_36;
        idex_control_jump <=
          ~(idCtrl_writeUpperImmediate | _GEN_28 | _GEN_29 | _GEN_30 | _GEN_32 | _GEN_41)
          & _GEN_40;
        idex_control_aluOp <=
          idCtrl_writeUpperImmediate | _GEN_31 | ~_GEN_30
            ? 4'h0
            : {3'h2, _idCtrl_aluOp_T};
        idex_control_aluSrcImmediate <=
          ~idCtrl_writeUpperImmediate
          & (_GEN_31 | ~_GEN_30 & (_GEN_37 | ~(_GEN_36 | _GEN_38) & _GEN_39));
        idex_control_loadSize <=
          _GEN_33 | ~_GEN_32 | ~(|(ifid_instr[14:12])) | _idCtrl_loadSize_T_1
            ? 2'h0
            : _idCtrl_storeSize_T_1 | _idCtrl_loadSize_T_4 ? 2'h1 : 2'h2;
        idex_control_loadSigned <=
          ~_GEN_33 & _GEN_32 & ifid_instr[14:12] != 3'h4 & _idCtrl_loadSigned_T_1;
        idex_control_storeSize <=
          _GEN_35 | ~(_GEN_34 & (|(ifid_instr[14:12])))
            ? 2'h0
            : _idCtrl_storeSize_T_1 ? 2'h1 : 2'h2;
        idex_control_writeUpperImmediate <= idCtrl_writeUpperImmediate;
        idex_control_writePcRelative <= ~idCtrl_writeUpperImmediate & _GEN_28;
        idex_control_illegal <=
          ifid_valid
          & (~(ifid_instr[6:0] == 7'h37 | ifid_instr[6:0] == 7'h17 | _idUsesRs1_T
               | _idUsesRs2_T | _idUsesRs1_T_3 | _idUsesRs2_T_1 | _idUsesRs2_T_3
               | ifid_instr[6:0] == 7'h6F | _idUsesRs1_T_9 | _scalarLegalFunct_T
               | _scalarLegalFunct_T_4 | _idCustomIllegal_T | _idCustomIllegal_T_1)
             | ~(_idCustomIllegal_T | _idCustomIllegal_T_1
                   ? (_idCustomIllegal_T
                        ? ~(ifid_instr[14])
                        : ~(|(ifid_instr[14:12])) | _idCtrl_isCubeWait_T)
                   : _scalarLegalFunct_T
                       ? ~(|(ifid_instr[14:12])) | _idCtrl_storeSize_T_1
                       : _scalarLegalFunct_T_4
                           ? ifid_instr == 32'h100073
                           : _idUsesRs1_T
                               ? (ifid_instr[14:12] != 3'h1 | _scalarLegalFunct_T_19)
                                 & (_idCtrl_loadSigned_T_1 | _scalarLegalFunct_T_19
                                    | _scalarLegalFunct_T_22)
                               : _idUsesRs2_T
                                   ? _scalarLegalFunct_T_19 | _idCtrl_aluOp_T
                                     | _scalarLegalFunct_T_22
                                     & (~(|(ifid_instr[14:12])) | _idCtrl_loadSize_T_4)
                                   : _idUsesRs1_T_3
                                       ? ~(|(ifid_instr[14:12])) | _idCtrl_storeSize_T_1
                                         | ifid_instr[14:12] == 3'h2
                                         | _idCtrl_loadSize_T_1 | _idCtrl_loadSize_T_4
                                       : _idUsesRs2_T_1
                                           ? ifid_instr[14:12] < 3'h3
                                           : _idUsesRs2_T_3
                                               ? ~(|(ifid_instr[14:12]))
                                                 | _idCtrl_storeSize_T_1
                                                 | _idCtrl_loadSize_T_1
                                                 | _idCtrl_loadSize_T_4
                                                 | ifid_instr[14:12] == 3'h6
                                                 | (&(ifid_instr[14:12]))
                                               : ~_idUsesRs1_T_9
                                                 | ~(|(ifid_instr[14:12]))));
        idex_control_isVector <=
          ~(idCtrl_writeUpperImmediate | _GEN_28 | _GEN_29 | _GEN_30 | _GEN_32 | _GEN_34
            | _GEN_36 | _GEN_38 | _GEN_39) & _GEN_42;
        idex_control_isCubeLaunch <= ~_GEN_44 & _GEN_43 & ~(|(ifid_instr[14:12]));
        idex_control_isCubeWait <= ~_GEN_44 & _GEN_43 & _idCtrl_isCubeWait_T;
      end
      exmem_valid <=
        ~_GEN_27
        & (canPipe
             ? _GEN_9
             : _GEN_19 ? ~(_GEN_20 | _GEN_17) & exmem_valid : ~_GEN_17 & exmem_valid);
      if (canPipe & _GEN_9) begin
        exmem_pc <= idex_pc;
        exmem_instr <= idex_instr;
        exmem_rd <= idex_rd;
        if (_launchMem_T_1)
          exmem_aluResult <= _exResult_T;
        else if (idex_control_writeUpperImmediate)
          exmem_aluResult <= idex_immediate;
        else if (idex_control_writePcRelative)
          exmem_aluResult <= _exResult_T_2;
        else if (idex_control_jump)
          exmem_aluResult <= _exResult_T_4;
        else if (_GEN_3)
          exmem_aluResult <= _GEN_5;
        else
          exmem_aluResult <= _GEN_8;
        exmem_control_regWrite <= idex_control_regWrite;
        exmem_control_memRead <= idex_control_memRead;
        exmem_control_memWrite <= idex_control_memWrite;
        exmem_control_memToReg <= idex_control_memToReg;
      end
      memwb_valid <=
        _GEN_27 | (canPipe ? _GEN_23 | _GEN_21 | _GEN_16 : _GEN_21 | _GEN_16);
      if (_GEN_27 | canPipe & _GEN_23) begin
        memwb_pc <= exmem_pc;
        memwb_instr <= exmem_instr;
        memwb_rd <= exmem_rd;
        memwb_aluResult <= exmem_aluResult;
        memwb_loadData <= 32'h0;
        memwb_control_regWrite <= exmem_control_regWrite;
        memwb_control_memToReg <= exmem_control_memToReg;
      end
      else begin
        if (_GEN_19 & _GEN_20 | _GEN_17) begin
          memwb_pc <= memPc;
          memwb_instr <= memInstr;
        end
        if (_GEN_17) begin
          automatic logic [3:0][7:0] _GEN_46 =
            {{io_axi_r_bits_data[31:24]},
             {io_axi_r_bits_data[23:16]},
             {io_axi_r_bits_data[15:8]},
             {io_axi_r_bits_data[7:0]}};
          automatic logic [7:0]      byte_0;
          automatic logic [15:0]     half;
          byte_0 = _GEN_46[memAddr[1:0]];
          half = memAddr[1] ? io_axi_r_bits_data[31:16] : io_axi_r_bits_data[15:0];
          memwb_rd <= memRd;
          memwb_loadData <=
            memSize == 2'h0
              ? {{24{byte_0[7] & memSigned}}, byte_0}
              : memSize == 2'h1 ? {{16{half[15] & memSigned}}, half} : io_axi_r_bits_data;
        end
        memwb_control_regWrite <=
          ~_GEN_21 & (_GEN_17 ? (|memRd) : memwb_control_regWrite);
        memwb_control_memToReg <= ~_GEN_21 & (_GEN_17 | memwb_control_memToReg);
      end
      if (_GEN_10)
        owner <= idex_control_memRead ? 3'h2 : 3'h4;
      else if (_GEN_19)
        owner <= 3'h0;
      else if (io_axi_w_valid_0 & io_axi_w_ready)
        owner <= 3'h6;
      else if (io_axi_aw_valid_0 & io_axi_aw_ready)
        owner <= 3'h5;
      else if (_GEN_15)
        owner <= 3'h0;
      else begin
        automatic logic _GEN_47;
        _GEN_47 = io_axi_ar_ready & io_axi_ar_valid_0;
        if (_io_axi_ar_bits_addr_T & _GEN_47)
          owner <= 3'h3;
        else if (fetchResponse)
          owner <= 3'h0;
        else if (_io_axi_ar_valid_T_1 & _GEN_47)
          owner <= 3'h1;
      end
      draining <= _GEN_26 | _GEN_22 | _GEN_18 | _GEN_14 | draining;
      halted <= draining & ~exmem_valid & ~memwb_valid & _io_axi_ar_valid_T_1 | halted;
      illegalSeen <= _GEN_0 | _GEN_22 | _GEN_18 | _GEN_14 | illegalSeen;
    end
    if (_GEN_10) begin
      automatic logic [31:0] exResult;
      automatic logic [94:0] _memData_T_2;
      automatic logic [4:0]  _memStrb_T_6;
      exResult =
        _launchMem_T_1
          ? _exResult_T
          : idex_control_writeUpperImmediate
              ? idex_immediate
              : idex_control_writePcRelative
                  ? _exResult_T_2
                  : idex_control_jump ? _exResult_T_4 : _GEN_3 ? _GEN_5 : _GEN_8;
      memAddr <= exResult;
      _memData_T_2 = {63'h0, exRs2} << {90'h0, exResult[1:0], 3'h0};
      memData <= _memData_T_2[31:0];
      _memStrb_T_6 = 5'h3 << {3'h0, exResult[1], 1'h0};
      memStrb <=
        idex_control_storeSize == 2'h0
          ? 4'h1 << exResult[1:0]
          : idex_control_storeSize == 2'h1 ? _memStrb_T_6[3:0] : 4'hF;
      memRd <= idex_rd;
      memPc <= idex_pc;
      memInstr <= idex_instr;
      memSize <= idex_control_memRead ? idex_control_loadSize : idex_control_storeSize;
      memSigned <= idex_control_loadSigned;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      automatic logic [31:0] _RANDOM[0:57];
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [5:0] i = 6'h0; i < 6'h3A; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        regs_0 = _RANDOM[6'h0];
        regs_1 = _RANDOM[6'h1];
        regs_2 = _RANDOM[6'h2];
        regs_3 = _RANDOM[6'h3];
        regs_4 = _RANDOM[6'h4];
        regs_5 = _RANDOM[6'h5];
        regs_6 = _RANDOM[6'h6];
        regs_7 = _RANDOM[6'h7];
        regs_8 = _RANDOM[6'h8];
        regs_9 = _RANDOM[6'h9];
        regs_10 = _RANDOM[6'hA];
        regs_11 = _RANDOM[6'hB];
        regs_12 = _RANDOM[6'hC];
        regs_13 = _RANDOM[6'hD];
        regs_14 = _RANDOM[6'hE];
        regs_15 = _RANDOM[6'hF];
        regs_16 = _RANDOM[6'h10];
        regs_17 = _RANDOM[6'h11];
        regs_18 = _RANDOM[6'h12];
        regs_19 = _RANDOM[6'h13];
        regs_20 = _RANDOM[6'h14];
        regs_21 = _RANDOM[6'h15];
        regs_22 = _RANDOM[6'h16];
        regs_23 = _RANDOM[6'h17];
        regs_24 = _RANDOM[6'h18];
        regs_25 = _RANDOM[6'h19];
        regs_26 = _RANDOM[6'h1A];
        regs_27 = _RANDOM[6'h1B];
        regs_28 = _RANDOM[6'h1C];
        regs_29 = _RANDOM[6'h1D];
        regs_30 = _RANDOM[6'h1E];
        regs_31 = _RANDOM[6'h1F];
        pc = _RANDOM[6'h20];
        ifid_valid = _RANDOM[6'h21][0];
        ifid_pc = {_RANDOM[6'h21][31:1], _RANDOM[6'h22][0]};
        ifid_instr = {_RANDOM[6'h22][31:1], _RANDOM[6'h23][0]};
        idex_valid = _RANDOM[6'h23][1];
        idex_pc = {_RANDOM[6'h23][31:2], _RANDOM[6'h24][1:0]};
        idex_instr = {_RANDOM[6'h24][31:2], _RANDOM[6'h25][1:0]};
        idex_rs1 = _RANDOM[6'h25][6:2];
        idex_rs2 = _RANDOM[6'h25][11:7];
        idex_rd = _RANDOM[6'h25][16:12];
        idex_rs1Data = {_RANDOM[6'h25][31:17], _RANDOM[6'h26][16:0]};
        idex_rs2Data = {_RANDOM[6'h26][31:17], _RANDOM[6'h27][16:0]};
        idex_immediate = {_RANDOM[6'h27][31:17], _RANDOM[6'h28][16:0]};
        idex_control_regWrite = _RANDOM[6'h28][17];
        idex_control_memRead = _RANDOM[6'h28][18];
        idex_control_memWrite = _RANDOM[6'h28][19];
        idex_control_memToReg = _RANDOM[6'h28][20];
        idex_control_branch = _RANDOM[6'h28][21];
        idex_control_jump = _RANDOM[6'h28][22];
        idex_control_aluOp = _RANDOM[6'h28][26:23];
        idex_control_aluSrcImmediate = _RANDOM[6'h28][27];
        idex_control_loadSize = _RANDOM[6'h28][29:28];
        idex_control_loadSigned = _RANDOM[6'h28][30];
        idex_control_storeSize = {_RANDOM[6'h28][31], _RANDOM[6'h29][0]};
        idex_control_writeUpperImmediate = _RANDOM[6'h29][5];
        idex_control_writePcRelative = _RANDOM[6'h29][6];
        idex_control_illegal = _RANDOM[6'h29][7];
        idex_control_isVector = _RANDOM[6'h29][8];
        idex_control_isCubeLaunch = _RANDOM[6'h29][11];
        idex_control_isCubeWait = _RANDOM[6'h29][12];
        exmem_valid = _RANDOM[6'h29][14];
        exmem_pc = {_RANDOM[6'h29][31:15], _RANDOM[6'h2A][14:0]};
        exmem_instr = {_RANDOM[6'h2A][31:15], _RANDOM[6'h2B][14:0]};
        exmem_rd = _RANDOM[6'h2B][19:15];
        exmem_aluResult = {_RANDOM[6'h2B][31:20], _RANDOM[6'h2C][19:0]};
        exmem_control_regWrite = _RANDOM[6'h2E][21];
        exmem_control_memRead = _RANDOM[6'h2E][22];
        exmem_control_memWrite = _RANDOM[6'h2E][23];
        exmem_control_memToReg = _RANDOM[6'h2E][24];
        memwb_valid = _RANDOM[6'h2F][18];
        memwb_pc = {_RANDOM[6'h2F][31:19], _RANDOM[6'h30][18:0]};
        memwb_instr = {_RANDOM[6'h30][31:19], _RANDOM[6'h31][18:0]};
        memwb_rd = _RANDOM[6'h31][23:19];
        memwb_aluResult = {_RANDOM[6'h31][31:24], _RANDOM[6'h32][23:0]};
        memwb_loadData = {_RANDOM[6'h32][31:24], _RANDOM[6'h33][23:0]};
        memwb_control_regWrite = _RANDOM[6'h33][24];
        memwb_control_memToReg = _RANDOM[6'h33][27];
        owner = _RANDOM[6'h34][23:21];
        memAddr = {_RANDOM[6'h34][31:24], _RANDOM[6'h35][23:0]};
        memData = {_RANDOM[6'h35][31:24], _RANDOM[6'h36][23:0]};
        memStrb = _RANDOM[6'h36][27:24];
        memRd = {_RANDOM[6'h36][31:28], _RANDOM[6'h37][0]};
        memPc = {_RANDOM[6'h37][31:1], _RANDOM[6'h38][0]};
        memInstr = {_RANDOM[6'h38][31:1], _RANDOM[6'h39][0]};
        memSize = _RANDOM[6'h39][2:1];
        memSigned = _RANDOM[6'h39][3];
        draining = _RANDOM[6'h39][5];
        halted = _RANDOM[6'h39][6];
        illegalSeen = _RANDOM[6'h39][7];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  VectorCore vectorCore (
    .io_issue_valid (io_debug_vector_issue_0),
    .io_issue_bits  (idex_rd[2:0]),
    .io_write       (io_debug_vector_write),
    .io_writeVd     (io_debug_vector_vd)
  );
  CubeCluster cubeCore (
    .clock          (clock),
    .reset          (reset),
    .io_launch      (_cubeCore_io_launch_T_3),
    .io_launchReady (_cubeCore_io_launchReady),
    .io_busy        (_cubeCore_io_busy),
    .io_done        (io_debug_cube_done)
  );
  assign io_axi_ar_valid = io_axi_ar_valid_0;
  assign io_axi_ar_bits_addr = _io_axi_ar_bits_addr_T ? io_axi_aw_bits_addr_0 : pc;
  assign io_axi_r_ready = io_axi_r_ready_0;
  assign io_axi_aw_valid = io_axi_aw_valid_0;
  assign io_axi_aw_bits_addr = io_axi_aw_bits_addr_0;
  assign io_axi_w_valid = io_axi_w_valid_0;
  assign io_axi_w_bits_data = memData;
  assign io_axi_w_bits_strb = memStrb;
  assign io_axi_b_ready = io_axi_b_ready_0;
  assign io_debug_commit = memwb_valid;
  assign io_debug_pc = memwb_valid ? memwb_pc : 32'h0;
  assign io_debug_instr = memwb_valid ? memwb_instr : 32'h0;
  assign io_debug_rd = memwb_valid ? memwb_rd : 5'h0;
  assign io_debug_wdata = memwb_valid ? wbValue : 32'h0;
  assign io_debug_wen = memwb_valid & memwb_control_regWrite & (|memwb_rd);
  assign io_debug_illegal = illegalSeen;
  assign io_debug_vector_issue = io_debug_vector_issue_0;
  assign io_debug_cube_launch = _cubeCore_io_launch_T_3 & _cubeCore_io_launchReady;
  assign io_debug_cube_busy = _cubeCore_io_busy;
  assign io_debug_cube_wait_stall = cubeWaitStall;
  assign io_debug_stall_reason =
    {1'h0, cubeWaitStall ? 3'h3 : cubeLaunchBlocked ? 3'h2 : {loadUse, 2'h0}};
  assign io_halted = halted;
endmodule

module AxiCache(
  input         clock,
                reset,
  output        io_cpu_ar_ready,
  input         io_cpu_ar_valid,
  input  [31:0] io_cpu_ar_bits_addr,
  input         io_cpu_r_ready,
  output        io_cpu_r_valid,
  output [3:0]  io_cpu_r_bits_id,
  output [31:0] io_cpu_r_bits_data,
  output [1:0]  io_cpu_r_bits_resp,
  output        io_cpu_r_bits_last,
                io_cpu_aw_ready,
  input         io_cpu_aw_valid,
  input  [31:0] io_cpu_aw_bits_addr,
  output        io_cpu_w_ready,
  input         io_cpu_w_valid,
  input  [31:0] io_cpu_w_bits_data,
  input  [3:0]  io_cpu_w_bits_strb,
  input         io_cpu_b_ready,
  output        io_cpu_b_valid,
  output [3:0]  io_cpu_b_bits_id,
  output [1:0]  io_cpu_b_bits_resp,
  input         io_mem_ar_ready,
  output        io_mem_ar_valid,
  output [3:0]  io_mem_ar_bits_id,
  output [31:0] io_mem_ar_bits_addr,
  output        io_mem_r_ready,
  input         io_mem_r_valid,
  input  [3:0]  io_mem_r_bits_id,
  input  [31:0] io_mem_r_bits_data,
  input  [1:0]  io_mem_r_bits_resp,
  input         io_mem_r_bits_last,
                io_mem_aw_ready,
  output        io_mem_aw_valid,
  output [31:0] io_mem_aw_bits_addr,
  input         io_mem_w_ready,
  output        io_mem_w_valid,
  output [31:0] io_mem_w_bits_data,
  output [3:0]  io_mem_w_bits_strb,
  output        io_mem_b_ready,
  input         io_mem_b_valid,
  input  [3:0]  io_mem_b_bits_id,
  input  [1:0]  io_mem_b_bits_resp
);

  reg         valid_0;
  reg         valid_1;
  reg         valid_2;
  reg         valid_3;
  reg  [27:0] tags_0;
  reg  [27:0] tags_1;
  reg  [27:0] tags_2;
  reg  [27:0] tags_3;
  reg  [31:0] data_0;
  reg  [31:0] data_1;
  reg  [31:0] data_2;
  reg  [31:0] data_3;
  reg  [2:0]  state;
  reg  [31:0] readAddr;
  reg  [3:0]  readId;
  reg  [1:0]  readIndex;
  reg  [27:0] readTag;
  reg  [31:0] readData;
  reg  [3:0]  readRespId;
  reg  [1:0]  readResp;
  reg         readLast;
  reg  [31:0] writeAddr;
  wire        _io_cpu_ar_ready_T = state == 3'h0;
  wire        io_cpu_aw_ready_0 = _io_cpu_ar_ready_T & io_cpu_aw_valid;
  wire        io_cpu_ar_ready_0 = _io_cpu_ar_ready_T & ~io_cpu_aw_valid;
  wire        io_cpu_r_valid_0 = state == 3'h3;
  wire        _io_mem_w_valid_T = state == 3'h5;
  wire        _io_mem_b_ready_T = state == 3'h6;
  wire        io_mem_ar_valid_0 = state == 3'h1;
  wire        io_mem_r_ready_0 = state == 3'h2;
  wire        io_mem_aw_valid_0 = state == 3'h4;
  wire        io_mem_w_valid_0 = _io_mem_w_valid_T & io_cpu_w_valid;
  wire        io_mem_b_ready_0 = _io_mem_b_ready_T & io_cpu_b_ready;
  always @(posedge clock) begin
    automatic logic [3:0]       _GEN;
    automatic logic [3:0][27:0] _GEN_0;
    automatic logic             hit;
    automatic logic             _GEN_1;
    automatic logic             _GEN_2;
    automatic logic             _GEN_3;
    automatic logic             _GEN_4;
    automatic logic             _GEN_5;
    automatic logic             _GEN_6;
    automatic logic             _GEN_7;
    automatic logic             _GEN_8;
    automatic logic             _GEN_9;
    _GEN = {{valid_3}, {valid_2}, {valid_1}, {valid_0}};
    _GEN_0 = {{tags_3}, {tags_2}, {tags_1}, {tags_0}};
    hit =
      _GEN[io_cpu_ar_bits_addr[3:2]]
      & _GEN_0[io_cpu_ar_bits_addr[3:2]] == io_cpu_ar_bits_addr[31:4];
    _GEN_1 = _io_cpu_ar_ready_T & io_cpu_aw_ready_0 & io_cpu_aw_valid;
    _GEN_2 = _io_cpu_ar_ready_T & io_cpu_ar_ready_0 & io_cpu_ar_valid;
    _GEN_3 = _GEN_1 | ~_GEN_2;
    _GEN_4 = io_mem_r_ready_0 & io_mem_r_valid;
    _GEN_5 = io_mem_r_bits_id == readId & io_mem_r_bits_resp == 2'h0 & io_mem_r_bits_last;
    _GEN_6 = _GEN_4 & _GEN_5 & readIndex == 2'h0;
    _GEN_7 = _GEN_4 & _GEN_5 & readIndex == 2'h1;
    _GEN_8 = _GEN_4 & _GEN_5 & readIndex == 2'h2;
    _GEN_9 = _GEN_4 & _GEN_5 & (&readIndex);
    if (reset) begin
      valid_0 <= 1'h0;
      valid_1 <= 1'h0;
      valid_2 <= 1'h0;
      valid_3 <= 1'h0;
      state <= 3'h0;
    end
    else begin
      valid_0 <= _GEN_6 | ~_GEN_1 & valid_0;
      valid_1 <= _GEN_7 | ~_GEN_1 & valid_1;
      valid_2 <= _GEN_8 | ~_GEN_1 & valid_2;
      valid_3 <= _GEN_9 | ~_GEN_1 & valid_3;
      if (_io_mem_b_ready_T & io_mem_b_ready_0 & io_mem_b_valid)
        state <= 3'h0;
      else if (_io_mem_w_valid_T & io_mem_w_ready & io_mem_w_valid_0)
        state <= 3'h6;
      else if (io_mem_aw_valid_0 & io_mem_aw_ready)
        state <= 3'h5;
      else if (io_cpu_r_valid_0 & io_cpu_r_ready)
        state <= 3'h0;
      else if (_GEN_4)
        state <= 3'h3;
      else if (io_mem_ar_valid_0 & io_mem_ar_ready)
        state <= 3'h2;
      else if (_GEN_1)
        state <= 3'h4;
      else if (_GEN_2)
        state <= {1'h0, hit, 1'h1};
    end
    if (_GEN_6) begin
      tags_0 <= readTag;
      data_0 <= io_mem_r_bits_data;
    end
    if (_GEN_7) begin
      tags_1 <= readTag;
      data_1 <= io_mem_r_bits_data;
    end
    if (_GEN_8) begin
      tags_2 <= readTag;
      data_2 <= io_mem_r_bits_data;
    end
    if (_GEN_9) begin
      tags_3 <= readTag;
      data_3 <= io_mem_r_bits_data;
    end
    if (_GEN_3) begin
    end
    else begin
      readAddr <= io_cpu_ar_bits_addr;
      readId <= 4'h0;
      readIndex <= io_cpu_ar_bits_addr[3:2];
      readTag <= io_cpu_ar_bits_addr[31:4];
    end
    if (_GEN_4) begin
      readData <= io_mem_r_bits_data;
      readRespId <= io_mem_r_bits_id;
      readResp <= io_mem_r_bits_resp;
      readLast <= io_mem_r_bits_last;
    end
    else begin
      if (_GEN_3) begin
      end
      else begin
        automatic logic [3:0][31:0] _GEN_10;
        _GEN_10 = {{data_3}, {data_2}, {data_1}, {data_0}};
        readData <= hit ? _GEN_10[io_cpu_ar_bits_addr[3:2]] : 32'h0;
        readRespId <= 4'h0;
        readResp <= 2'h0;
      end
      readLast <= ~_GEN_1 & _GEN_2 | readLast;
    end
    if (_GEN_1)
      writeAddr <= io_cpu_aw_bits_addr;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      automatic logic [31:0] _RANDOM[0:11];
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'hC; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        valid_0 = _RANDOM[4'h0][0];
        valid_1 = _RANDOM[4'h0][1];
        valid_2 = _RANDOM[4'h0][2];
        valid_3 = _RANDOM[4'h0][3];
        tags_0 = _RANDOM[4'h0][31:4];
        tags_1 = _RANDOM[4'h1][27:0];
        tags_2 = {_RANDOM[4'h1][31:28], _RANDOM[4'h2][23:0]};
        tags_3 = {_RANDOM[4'h2][31:24], _RANDOM[4'h3][19:0]};
        data_0 = {_RANDOM[4'h3][31:20], _RANDOM[4'h4][19:0]};
        data_1 = {_RANDOM[4'h4][31:20], _RANDOM[4'h5][19:0]};
        data_2 = {_RANDOM[4'h5][31:20], _RANDOM[4'h6][19:0]};
        data_3 = {_RANDOM[4'h6][31:20], _RANDOM[4'h7][19:0]};
        state = _RANDOM[4'h7][22:20];
        readAddr = {_RANDOM[4'h7][31:23], _RANDOM[4'h8][22:0]};
        readId = _RANDOM[4'h8][26:23];
        readIndex = _RANDOM[4'h8][28:27];
        readTag = {_RANDOM[4'h8][31:29], _RANDOM[4'h9][24:0]};
        readData = {_RANDOM[4'h9][31:25], _RANDOM[4'hA][24:0]};
        readRespId = _RANDOM[4'hA][28:25];
        readResp = _RANDOM[4'hA][30:29];
        readLast = _RANDOM[4'hA][31];
        writeAddr = _RANDOM[4'hB];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_cpu_ar_ready = io_cpu_ar_ready_0;
  assign io_cpu_r_valid = io_cpu_r_valid_0;
  assign io_cpu_r_bits_id = readRespId;
  assign io_cpu_r_bits_data = readData;
  assign io_cpu_r_bits_resp = readResp;
  assign io_cpu_r_bits_last = readLast;
  assign io_cpu_aw_ready = io_cpu_aw_ready_0;
  assign io_cpu_w_ready = _io_mem_w_valid_T & io_mem_w_ready;
  assign io_cpu_b_valid = _io_mem_b_ready_T & io_mem_b_valid;
  assign io_cpu_b_bits_id = io_mem_b_bits_id;
  assign io_cpu_b_bits_resp = io_mem_b_bits_resp;
  assign io_mem_ar_valid = io_mem_ar_valid_0;
  assign io_mem_ar_bits_id = readId;
  assign io_mem_ar_bits_addr = readAddr & 32'hFFFFFFFC;
  assign io_mem_r_ready = io_mem_r_ready_0;
  assign io_mem_aw_valid = io_mem_aw_valid_0;
  assign io_mem_aw_bits_addr = writeAddr & 32'hFFFFFFFC;
  assign io_mem_w_valid = io_mem_w_valid_0;
  assign io_mem_w_bits_data = io_cpu_w_bits_data;
  assign io_mem_w_bits_strb = io_cpu_w_bits_strb;
  assign io_mem_b_ready = io_mem_b_ready_0;
endmodule

module core_top(
  input         clock,
                reset,
                io_mei,
                io_msi,
                io_mti,
                io_sei,
                io_axi_ar_ready,
  output        io_axi_ar_valid,
  output [3:0]  io_axi_ar_bits_id,
  output [31:0] io_axi_ar_bits_addr,
  output [7:0]  io_axi_ar_bits_len,
  output [2:0]  io_axi_ar_bits_size,
  output [1:0]  io_axi_ar_bits_burst,
  output [2:0]  io_axi_ar_bits_prot,
  output        io_axi_r_ready,
  input         io_axi_r_valid,
  input  [3:0]  io_axi_r_bits_id,
  input  [31:0] io_axi_r_bits_data,
  input  [1:0]  io_axi_r_bits_resp,
  input         io_axi_r_bits_last,
                io_axi_aw_ready,
  output        io_axi_aw_valid,
  output [3:0]  io_axi_aw_bits_id,
  output [31:0] io_axi_aw_bits_addr,
  output [7:0]  io_axi_aw_bits_len,
  output [2:0]  io_axi_aw_bits_size,
  output [1:0]  io_axi_aw_bits_burst,
  output [2:0]  io_axi_aw_bits_prot,
  input         io_axi_w_ready,
  output        io_axi_w_valid,
  output [3:0]  io_axi_w_bits_id,
  output [31:0] io_axi_w_bits_data,
  output [3:0]  io_axi_w_bits_strb,
  output        io_axi_w_bits_last,
                io_axi_b_ready,
  input         io_axi_b_valid,
  input  [3:0]  io_axi_b_bits_id,
  input  [1:0]  io_axi_b_bits_resp,
  output        io_debug_commit,
  output [31:0] io_debug_pc,
                io_debug_instr,
  output [4:0]  io_debug_rf_wnum,
  output [31:0] io_debug_rf_wdata,
  output        io_debug_rf_wen,
                io_debug_illegal,
                io_halted,
                io_debug_vector_issue,
                io_debug_vector_write,
  output [2:0]  io_debug_vector_vd,
  output        io_debug_cube_launch,
                io_debug_cube_busy,
                io_debug_cube_done,
                io_debug_cube_wait_stall,
  output [3:0]  io_debug_stall_reason
);

  wire        _cache_io_cpu_ar_ready;
  wire        _cache_io_cpu_r_valid;
  wire [3:0]  _cache_io_cpu_r_bits_id;
  wire [31:0] _cache_io_cpu_r_bits_data;
  wire [1:0]  _cache_io_cpu_r_bits_resp;
  wire        _cache_io_cpu_r_bits_last;
  wire        _cache_io_cpu_aw_ready;
  wire        _cache_io_cpu_w_ready;
  wire        _cache_io_cpu_b_valid;
  wire [3:0]  _cache_io_cpu_b_bits_id;
  wire [1:0]  _cache_io_cpu_b_bits_resp;
  wire        _core_io_axi_ar_valid;
  wire [31:0] _core_io_axi_ar_bits_addr;
  wire        _core_io_axi_r_ready;
  wire        _core_io_axi_aw_valid;
  wire [31:0] _core_io_axi_aw_bits_addr;
  wire        _core_io_axi_w_valid;
  wire [31:0] _core_io_axi_w_bits_data;
  wire [3:0]  _core_io_axi_w_bits_strb;
  wire        _core_io_axi_b_ready;
  Core core (
    .clock                    (clock),
    .reset                    (reset),
    .io_axi_ar_ready          (_cache_io_cpu_ar_ready),
    .io_axi_ar_valid          (_core_io_axi_ar_valid),
    .io_axi_ar_bits_addr      (_core_io_axi_ar_bits_addr),
    .io_axi_r_ready           (_core_io_axi_r_ready),
    .io_axi_r_valid           (_cache_io_cpu_r_valid),
    .io_axi_r_bits_id         (_cache_io_cpu_r_bits_id),
    .io_axi_r_bits_data       (_cache_io_cpu_r_bits_data),
    .io_axi_r_bits_resp       (_cache_io_cpu_r_bits_resp),
    .io_axi_r_bits_last       (_cache_io_cpu_r_bits_last),
    .io_axi_aw_ready          (_cache_io_cpu_aw_ready),
    .io_axi_aw_valid          (_core_io_axi_aw_valid),
    .io_axi_aw_bits_addr      (_core_io_axi_aw_bits_addr),
    .io_axi_w_ready           (_cache_io_cpu_w_ready),
    .io_axi_w_valid           (_core_io_axi_w_valid),
    .io_axi_w_bits_data       (_core_io_axi_w_bits_data),
    .io_axi_w_bits_strb       (_core_io_axi_w_bits_strb),
    .io_axi_b_ready           (_core_io_axi_b_ready),
    .io_axi_b_valid           (_cache_io_cpu_b_valid),
    .io_axi_b_bits_id         (_cache_io_cpu_b_bits_id),
    .io_axi_b_bits_resp       (_cache_io_cpu_b_bits_resp),
    .io_debug_commit          (io_debug_commit),
    .io_debug_pc              (io_debug_pc),
    .io_debug_instr           (io_debug_instr),
    .io_debug_rd              (io_debug_rf_wnum),
    .io_debug_wdata           (io_debug_rf_wdata),
    .io_debug_wen             (io_debug_rf_wen),
    .io_debug_illegal         (io_debug_illegal),
    .io_debug_vector_issue    (io_debug_vector_issue),
    .io_debug_vector_write    (io_debug_vector_write),
    .io_debug_vector_vd       (io_debug_vector_vd),
    .io_debug_cube_launch     (io_debug_cube_launch),
    .io_debug_cube_busy       (io_debug_cube_busy),
    .io_debug_cube_done       (io_debug_cube_done),
    .io_debug_cube_wait_stall (io_debug_cube_wait_stall),
    .io_debug_stall_reason    (io_debug_stall_reason),
    .io_halted                (io_halted)
  );
  AxiCache cache (
    .clock               (clock),
    .reset               (reset),
    .io_cpu_ar_ready     (_cache_io_cpu_ar_ready),
    .io_cpu_ar_valid     (_core_io_axi_ar_valid),
    .io_cpu_ar_bits_addr (_core_io_axi_ar_bits_addr),
    .io_cpu_r_ready      (_core_io_axi_r_ready),
    .io_cpu_r_valid      (_cache_io_cpu_r_valid),
    .io_cpu_r_bits_id    (_cache_io_cpu_r_bits_id),
    .io_cpu_r_bits_data  (_cache_io_cpu_r_bits_data),
    .io_cpu_r_bits_resp  (_cache_io_cpu_r_bits_resp),
    .io_cpu_r_bits_last  (_cache_io_cpu_r_bits_last),
    .io_cpu_aw_ready     (_cache_io_cpu_aw_ready),
    .io_cpu_aw_valid     (_core_io_axi_aw_valid),
    .io_cpu_aw_bits_addr (_core_io_axi_aw_bits_addr),
    .io_cpu_w_ready      (_cache_io_cpu_w_ready),
    .io_cpu_w_valid      (_core_io_axi_w_valid),
    .io_cpu_w_bits_data  (_core_io_axi_w_bits_data),
    .io_cpu_w_bits_strb  (_core_io_axi_w_bits_strb),
    .io_cpu_b_ready      (_core_io_axi_b_ready),
    .io_cpu_b_valid      (_cache_io_cpu_b_valid),
    .io_cpu_b_bits_id    (_cache_io_cpu_b_bits_id),
    .io_cpu_b_bits_resp  (_cache_io_cpu_b_bits_resp),
    .io_mem_ar_ready     (io_axi_ar_ready),
    .io_mem_ar_valid     (io_axi_ar_valid),
    .io_mem_ar_bits_id   (io_axi_ar_bits_id),
    .io_mem_ar_bits_addr (io_axi_ar_bits_addr),
    .io_mem_r_ready      (io_axi_r_ready),
    .io_mem_r_valid      (io_axi_r_valid),
    .io_mem_r_bits_id    (io_axi_r_bits_id),
    .io_mem_r_bits_data  (io_axi_r_bits_data),
    .io_mem_r_bits_resp  (io_axi_r_bits_resp),
    .io_mem_r_bits_last  (io_axi_r_bits_last),
    .io_mem_aw_ready     (io_axi_aw_ready),
    .io_mem_aw_valid     (io_axi_aw_valid),
    .io_mem_aw_bits_addr (io_axi_aw_bits_addr),
    .io_mem_w_ready      (io_axi_w_ready),
    .io_mem_w_valid      (io_axi_w_valid),
    .io_mem_w_bits_data  (io_axi_w_bits_data),
    .io_mem_w_bits_strb  (io_axi_w_bits_strb),
    .io_mem_b_ready      (io_axi_b_ready),
    .io_mem_b_valid      (io_axi_b_valid),
    .io_mem_b_bits_id    (io_axi_b_bits_id),
    .io_mem_b_bits_resp  (io_axi_b_bits_resp)
  );
  assign io_axi_ar_bits_len = 8'h0;
  assign io_axi_ar_bits_size = 3'h2;
  assign io_axi_ar_bits_burst = 2'h1;
  assign io_axi_ar_bits_prot = 3'h0;
  assign io_axi_aw_bits_id = 4'h1;
  assign io_axi_aw_bits_len = 8'h0;
  assign io_axi_aw_bits_size = 3'h2;
  assign io_axi_aw_bits_burst = 2'h1;
  assign io_axi_aw_bits_prot = 3'h0;
  assign io_axi_w_bits_id = 4'h1;
  assign io_axi_w_bits_last = 1'h1;
endmodule

